// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/param/param.proto

package param

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitNDIDParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitNDIDParam) Reset()         { *m = InitNDIDParam{} }
func (m *InitNDIDParam) String() string { return proto.CompactTextString(m) }
func (*InitNDIDParam) ProtoMessage()    {}
func (*InitNDIDParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{0}
}
func (m *InitNDIDParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitNDIDParam.Unmarshal(m, b)
}
func (m *InitNDIDParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitNDIDParam.Marshal(b, m, deterministic)
}
func (dst *InitNDIDParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitNDIDParam.Merge(dst, src)
}
func (m *InitNDIDParam) XXX_Size() int {
	return xxx_messageInfo_InitNDIDParam.Size(m)
}
func (m *InitNDIDParam) XXX_DiscardUnknown() {
	xxx_messageInfo_InitNDIDParam.DiscardUnknown(m)
}

var xxx_messageInfo_InitNDIDParam proto.InternalMessageInfo

func (m *InitNDIDParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *InitNDIDParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *InitNDIDParam) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type RegisterNodeParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,6,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,7,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeParam) Reset()         { *m = RegisterNodeParam{} }
func (m *RegisterNodeParam) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeParam) ProtoMessage()    {}
func (*RegisterNodeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{1}
}
func (m *RegisterNodeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeParam.Unmarshal(m, b)
}
func (m *RegisterNodeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeParam.Marshal(b, m, deterministic)
}
func (dst *RegisterNodeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeParam.Merge(dst, src)
}
func (m *RegisterNodeParam) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeParam.Size(m)
}
func (m *RegisterNodeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeParam.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeParam proto.InternalMessageInfo

func (m *RegisterNodeParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RegisterNodeParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RegisterNodeParam) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *RegisterNodeParam) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *RegisterNodeParam) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RegisterNodeParam) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *RegisterNodeParam) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

type UpdateNodeParam struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeParam) Reset()         { *m = UpdateNodeParam{} }
func (m *UpdateNodeParam) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeParam) ProtoMessage()    {}
func (*UpdateNodeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{2}
}
func (m *UpdateNodeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeParam.Unmarshal(m, b)
}
func (m *UpdateNodeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeParam.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeParam.Merge(dst, src)
}
func (m *UpdateNodeParam) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeParam.Size(m)
}
func (m *UpdateNodeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeParam.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeParam proto.InternalMessageInfo

func (m *UpdateNodeParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UpdateNodeParam) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type SetValidatorParam struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Power                int64    `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValidatorParam) Reset()         { *m = SetValidatorParam{} }
func (m *SetValidatorParam) String() string { return proto.CompactTextString(m) }
func (*SetValidatorParam) ProtoMessage()    {}
func (*SetValidatorParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{3}
}
func (m *SetValidatorParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValidatorParam.Unmarshal(m, b)
}
func (m *SetValidatorParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValidatorParam.Marshal(b, m, deterministic)
}
func (dst *SetValidatorParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValidatorParam.Merge(dst, src)
}
func (m *SetValidatorParam) XXX_Size() int {
	return xxx_messageInfo_SetValidatorParam.Size(m)
}
func (m *SetValidatorParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValidatorParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetValidatorParam proto.InternalMessageInfo

func (m *SetValidatorParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SetValidatorParam) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type SetPriceFuncParam struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPriceFuncParam) Reset()         { *m = SetPriceFuncParam{} }
func (m *SetPriceFuncParam) String() string { return proto.CompactTextString(m) }
func (*SetPriceFuncParam) ProtoMessage()    {}
func (*SetPriceFuncParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{4}
}
func (m *SetPriceFuncParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPriceFuncParam.Unmarshal(m, b)
}
func (m *SetPriceFuncParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPriceFuncParam.Marshal(b, m, deterministic)
}
func (dst *SetPriceFuncParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPriceFuncParam.Merge(dst, src)
}
func (m *SetPriceFuncParam) XXX_Size() int {
	return xxx_messageInfo_SetPriceFuncParam.Size(m)
}
func (m *SetPriceFuncParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPriceFuncParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetPriceFuncParam proto.InternalMessageInfo

func (m *SetPriceFuncParam) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *SetPriceFuncParam) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetPriceFuncParam struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceFuncParam) Reset()         { *m = GetPriceFuncParam{} }
func (m *GetPriceFuncParam) String() string { return proto.CompactTextString(m) }
func (*GetPriceFuncParam) ProtoMessage()    {}
func (*GetPriceFuncParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{5}
}
func (m *GetPriceFuncParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceFuncParam.Unmarshal(m, b)
}
func (m *GetPriceFuncParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceFuncParam.Marshal(b, m, deterministic)
}
func (dst *GetPriceFuncParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceFuncParam.Merge(dst, src)
}
func (m *GetPriceFuncParam) XXX_Size() int {
	return xxx_messageInfo_GetPriceFuncParam.Size(m)
}
func (m *GetPriceFuncParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceFuncParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceFuncParam proto.InternalMessageInfo

func (m *GetPriceFuncParam) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type SetNodeTokenParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodeTokenParam) Reset()         { *m = SetNodeTokenParam{} }
func (m *SetNodeTokenParam) String() string { return proto.CompactTextString(m) }
func (*SetNodeTokenParam) ProtoMessage()    {}
func (*SetNodeTokenParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{6}
}
func (m *SetNodeTokenParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodeTokenParam.Unmarshal(m, b)
}
func (m *SetNodeTokenParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodeTokenParam.Marshal(b, m, deterministic)
}
func (dst *SetNodeTokenParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodeTokenParam.Merge(dst, src)
}
func (m *SetNodeTokenParam) XXX_Size() int {
	return xxx_messageInfo_SetNodeTokenParam.Size(m)
}
func (m *SetNodeTokenParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodeTokenParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodeTokenParam proto.InternalMessageInfo

func (m *SetNodeTokenParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SetNodeTokenParam) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type AddNodeTokenParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeTokenParam) Reset()         { *m = AddNodeTokenParam{} }
func (m *AddNodeTokenParam) String() string { return proto.CompactTextString(m) }
func (*AddNodeTokenParam) ProtoMessage()    {}
func (*AddNodeTokenParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{7}
}
func (m *AddNodeTokenParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeTokenParam.Unmarshal(m, b)
}
func (m *AddNodeTokenParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeTokenParam.Marshal(b, m, deterministic)
}
func (dst *AddNodeTokenParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeTokenParam.Merge(dst, src)
}
func (m *AddNodeTokenParam) XXX_Size() int {
	return xxx_messageInfo_AddNodeTokenParam.Size(m)
}
func (m *AddNodeTokenParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeTokenParam.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeTokenParam proto.InternalMessageInfo

func (m *AddNodeTokenParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddNodeTokenParam) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReduceNodeTokenParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceNodeTokenParam) Reset()         { *m = ReduceNodeTokenParam{} }
func (m *ReduceNodeTokenParam) String() string { return proto.CompactTextString(m) }
func (*ReduceNodeTokenParam) ProtoMessage()    {}
func (*ReduceNodeTokenParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{8}
}
func (m *ReduceNodeTokenParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceNodeTokenParam.Unmarshal(m, b)
}
func (m *ReduceNodeTokenParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceNodeTokenParam.Marshal(b, m, deterministic)
}
func (dst *ReduceNodeTokenParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceNodeTokenParam.Merge(dst, src)
}
func (m *ReduceNodeTokenParam) XXX_Size() int {
	return xxx_messageInfo_ReduceNodeTokenParam.Size(m)
}
func (m *ReduceNodeTokenParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceNodeTokenParam.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceNodeTokenParam proto.InternalMessageInfo

func (m *ReduceNodeTokenParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ReduceNodeTokenParam) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GetNodeTokenParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeTokenParam) Reset()         { *m = GetNodeTokenParam{} }
func (m *GetNodeTokenParam) String() string { return proto.CompactTextString(m) }
func (*GetNodeTokenParam) ProtoMessage()    {}
func (*GetNodeTokenParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{9}
}
func (m *GetNodeTokenParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeTokenParam.Unmarshal(m, b)
}
func (m *GetNodeTokenParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeTokenParam.Marshal(b, m, deterministic)
}
func (dst *GetNodeTokenParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeTokenParam.Merge(dst, src)
}
func (m *GetNodeTokenParam) XXX_Size() int {
	return xxx_messageInfo_GetNodeTokenParam.Size(m)
}
func (m *GetNodeTokenParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeTokenParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeTokenParam proto.InternalMessageInfo

func (m *GetNodeTokenParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type CreateRequestParam struct {
	RequestId            string                `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64                 `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64               `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64               `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64                 `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	DataRequestList      []*DataRequestInParam `protobuf:"bytes,6,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string                `protobuf:"bytes,7,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	ResponseList         []*ResponseInParam    `protobuf:"bytes,8,rep,name=response_list,json=responseList,proto3" json:"response_list,omitempty"`
	Closed               bool                  `protobuf:"varint,9,opt,name=closed,proto3" json:"closed,omitempty"`
	TimedOut             bool                  `protobuf:"varint,10,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	CanAddAccessor       bool                  `protobuf:"varint,11,opt,name=can_add_accessor,json=canAddAccessor,proto3" json:"can_add_accessor,omitempty"`
	Owner                string                `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"`
	Mode                 int64                 `protobuf:"varint,13,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateRequestParam) Reset()         { *m = CreateRequestParam{} }
func (m *CreateRequestParam) String() string { return proto.CompactTextString(m) }
func (*CreateRequestParam) ProtoMessage()    {}
func (*CreateRequestParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{10}
}
func (m *CreateRequestParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestParam.Unmarshal(m, b)
}
func (m *CreateRequestParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestParam.Marshal(b, m, deterministic)
}
func (dst *CreateRequestParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestParam.Merge(dst, src)
}
func (m *CreateRequestParam) XXX_Size() int {
	return xxx_messageInfo_CreateRequestParam.Size(m)
}
func (m *CreateRequestParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestParam.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestParam proto.InternalMessageInfo

func (m *CreateRequestParam) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateRequestParam) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *CreateRequestParam) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *CreateRequestParam) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *CreateRequestParam) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *CreateRequestParam) GetDataRequestList() []*DataRequestInParam {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *CreateRequestParam) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *CreateRequestParam) GetResponseList() []*ResponseInParam {
	if m != nil {
		return m.ResponseList
	}
	return nil
}

func (m *CreateRequestParam) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *CreateRequestParam) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *CreateRequestParam) GetCanAddAccessor() bool {
	if m != nil {
		return m.CanAddAccessor
	}
	return false
}

func (m *CreateRequestParam) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateRequestParam) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type DataRequestInParam struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	RequestParamsHash    string   `protobuf:"bytes,4,opt,name=request_params_hash,json=requestParamsHash,proto3" json:"request_params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequestInParam) Reset()         { *m = DataRequestInParam{} }
func (m *DataRequestInParam) String() string { return proto.CompactTextString(m) }
func (*DataRequestInParam) ProtoMessage()    {}
func (*DataRequestInParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{11}
}
func (m *DataRequestInParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequestInParam.Unmarshal(m, b)
}
func (m *DataRequestInParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequestInParam.Marshal(b, m, deterministic)
}
func (dst *DataRequestInParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequestInParam.Merge(dst, src)
}
func (m *DataRequestInParam) XXX_Size() int {
	return xxx_messageInfo_DataRequestInParam.Size(m)
}
func (m *DataRequestInParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequestInParam.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequestInParam proto.InternalMessageInfo

func (m *DataRequestInParam) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequestInParam) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequestInParam) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequestInParam) GetRequestParamsHash() string {
	if m != nil {
		return m.RequestParamsHash
	}
	return ""
}

func (m *DataRequestInParam) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequestInParam) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type ResponseInParam struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,2,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityProof        string   `protobuf:"bytes,5,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	PrivateProofHash     string   `protobuf:"bytes,6,opt,name=private_proof_hash,json=privateProofHash,proto3" json:"private_proof_hash,omitempty"`
	IdpId                string   `protobuf:"bytes,7,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	ValidProof           string   `protobuf:"bytes,8,opt,name=valid_proof,json=validProof,proto3" json:"valid_proof,omitempty"`
	ValidIal             string   `protobuf:"bytes,9,opt,name=valid_ial,json=validIal,proto3" json:"valid_ial,omitempty"`
	ValidSignature       string   `protobuf:"bytes,10,opt,name=valid_signature,json=validSignature,proto3" json:"valid_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInParam) Reset()         { *m = ResponseInParam{} }
func (m *ResponseInParam) String() string { return proto.CompactTextString(m) }
func (*ResponseInParam) ProtoMessage()    {}
func (*ResponseInParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_79ea1fef2a5d6505, []int{12}
}
func (m *ResponseInParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInParam.Unmarshal(m, b)
}
func (m *ResponseInParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInParam.Marshal(b, m, deterministic)
}
func (dst *ResponseInParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInParam.Merge(dst, src)
}
func (m *ResponseInParam) XXX_Size() int {
	return xxx_messageInfo_ResponseInParam.Size(m)
}
func (m *ResponseInParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInParam.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInParam proto.InternalMessageInfo

func (m *ResponseInParam) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *ResponseInParam) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *ResponseInParam) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResponseInParam) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ResponseInParam) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *ResponseInParam) GetPrivateProofHash() string {
	if m != nil {
		return m.PrivateProofHash
	}
	return ""
}

func (m *ResponseInParam) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

func (m *ResponseInParam) GetValidProof() string {
	if m != nil {
		return m.ValidProof
	}
	return ""
}

func (m *ResponseInParam) GetValidIal() string {
	if m != nil {
		return m.ValidIal
	}
	return ""
}

func (m *ResponseInParam) GetValidSignature() string {
	if m != nil {
		return m.ValidSignature
	}
	return ""
}

func init() {
	proto.RegisterType((*InitNDIDParam)(nil), "InitNDIDParam")
	proto.RegisterType((*RegisterNodeParam)(nil), "RegisterNodeParam")
	proto.RegisterType((*UpdateNodeParam)(nil), "UpdateNodeParam")
	proto.RegisterType((*SetValidatorParam)(nil), "SetValidatorParam")
	proto.RegisterType((*SetPriceFuncParam)(nil), "SetPriceFuncParam")
	proto.RegisterType((*GetPriceFuncParam)(nil), "GetPriceFuncParam")
	proto.RegisterType((*SetNodeTokenParam)(nil), "SetNodeTokenParam")
	proto.RegisterType((*AddNodeTokenParam)(nil), "AddNodeTokenParam")
	proto.RegisterType((*ReduceNodeTokenParam)(nil), "ReduceNodeTokenParam")
	proto.RegisterType((*GetNodeTokenParam)(nil), "GetNodeTokenParam")
	proto.RegisterType((*CreateRequestParam)(nil), "CreateRequestParam")
	proto.RegisterType((*DataRequestInParam)(nil), "DataRequestInParam")
	proto.RegisterType((*ResponseInParam)(nil), "ResponseInParam")
}

func init() { proto.RegisterFile("protos/param/param.proto", fileDescriptor_param_79ea1fef2a5d6505) }

var fileDescriptor_param_79ea1fef2a5d6505 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x6d, 0x6b, 0xdc, 0x46,
	0x10, 0x46, 0x96, 0x4f, 0x39, 0x8d, 0x63, 0xdf, 0xdd, 0xda, 0x49, 0x04, 0x49, 0xe9, 0x21, 0x28,
	0x39, 0x4a, 0xea, 0x96, 0x96, 0x7c, 0x2c, 0xe5, 0xa8, 0x49, 0x22, 0xda, 0xba, 0x46, 0x49, 0xfb,
	0xa9, 0x20, 0x36, 0xda, 0xb1, 0xbd, 0x44, 0xd2, 0xaa, 0xbb, 0x2b, 0x3b, 0xfe, 0x73, 0xfd, 0x21,
	0xf9, 0x31, 0xa5, 0xec, 0xec, 0x2a, 0xe7, 0xbe, 0x40, 0x0f, 0x02, 0xf9, 0x72, 0xec, 0x3c, 0x33,
	0x3b, 0xcf, 0xcd, 0xcc, 0xb3, 0x23, 0xc8, 0x7a, 0xad, 0xac, 0x32, 0x5f, 0xf6, 0x5c, 0xf3, 0xd6,
	0xff, 0x1e, 0x13, 0x94, 0x1b, 0xd8, 0x2f, 0x3a, 0x69, 0x4f, 0x4f, 0x8a, 0x93, 0x33, 0x07, 0xb3,
	0x07, 0x70, 0xa7, 0x53, 0x02, 0x2b, 0x29, 0xb2, 0x68, 0x19, 0xad, 0xd2, 0x32, 0x71, 0x66, 0x21,
	0xd8, 0x27, 0x00, 0xfd, 0xf0, 0xba, 0x91, 0x75, 0xf5, 0x06, 0x6f, 0xb2, 0x1d, 0xf2, 0xa5, 0x1e,
	0xf9, 0x01, 0x6f, 0xd8, 0xe7, 0xb0, 0x68, 0xb9, 0xb1, 0xa8, 0xab, 0x5b, 0x51, 0x31, 0x45, 0xcd,
	0xbc, 0xe3, 0x6c, 0x8c, 0xcd, 0xdf, 0x45, 0xb0, 0x28, 0xf1, 0x42, 0x3a, 0xf4, 0x54, 0x09, 0xfc,
	0x68, 0xcc, 0xec, 0x21, 0xa4, 0xc4, 0xd1, 0xf1, 0x16, 0xb3, 0x5d, 0x8a, 0x99, 0x3a, 0xe0, 0x94,
	0xb7, 0xc8, 0x18, 0xec, 0x6a, 0xd5, 0x60, 0x36, 0x21, 0x9c, 0xce, 0xee, 0x4f, 0xb5, 0xfc, 0x6d,
	0x25, 0x79, 0x93, 0x25, 0xcb, 0x68, 0x15, 0x95, 0x49, 0xcb, 0xdf, 0x16, 0xbc, 0x19, 0x1d, 0x9c,
	0x37, 0xd9, 0x9d, 0xf7, 0x8e, 0x35, 0x6f, 0xf2, 0xdf, 0x60, 0xf6, 0x4b, 0x2f, 0xb8, 0xc5, 0x4d,
	0x65, 0x7f, 0x2f, 0x20, 0xda, 0xaa, 0x80, 0x9d, 0xff, 0x6e, 0xdd, 0x0b, 0x58, 0xbc, 0x44, 0xfb,
	0x2b, 0x6f, 0xa4, 0xe0, 0x56, 0xe9, 0xad, 0xf2, 0x1f, 0xc1, 0xa4, 0x57, 0xd7, 0xa8, 0x29, 0x67,
	0x5c, 0x7a, 0x23, 0xff, 0x96, 0x32, 0x9d, 0x69, 0x59, 0xe3, 0xb3, 0xa1, 0xab, 0x7d, 0x26, 0x06,
	0xbb, 0xe7, 0x43, 0x57, 0x87, 0x1c, 0x74, 0xa6, 0xeb, 0x2e, 0x8a, 0xae, 0x47, 0xa5, 0x37, 0xf2,
	0xc7, 0xb0, 0x78, 0xbe, 0xcd, 0xf5, 0xfc, 0x84, 0x78, 0x5c, 0x33, 0x5e, 0xa9, 0x37, 0xd8, 0xfd,
	0xcf, 0xac, 0xef, 0x43, 0xc2, 0x5b, 0x35, 0x74, 0x36, 0xb0, 0x05, 0xcb, 0x65, 0x59, 0x0b, 0xf1,
	0xa1, 0x59, 0x9e, 0xc3, 0x51, 0x89, 0x62, 0xa8, 0xf1, 0x43, 0x13, 0x3d, 0xa1, 0xea, 0xb7, 0xcc,
	0x92, 0xbf, 0x8b, 0x81, 0x7d, 0xaf, 0x91, 0x5b, 0x2c, 0xf1, 0xf7, 0x01, 0x8d, 0x7d, 0x3f, 0x36,
	0xed, 0xed, 0xcd, 0x95, 0x34, 0x20, 0x85, 0x20, 0x85, 0xc9, 0xae, 0x92, 0xa2, 0x0f, 0x83, 0x4b,
	0x5a, 0xd9, 0x15, 0xa2, 0x1f, 0x1d, 0x4e, 0x7a, 0x71, 0x90, 0x9e, 0xec, 0xd6, 0x41, 0x93, 0xee,
	0x06, 0x6f, 0x48, 0xdb, 0xde, 0xe1, 0xc4, 0xfa, 0x18, 0x66, 0x23, 0x93, 0x95, 0x2d, 0xaa, 0xc1,
	0x92, 0xc8, 0xe3, 0xf2, 0x20, 0xc0, 0xaf, 0x3c, 0xca, 0xbe, 0x83, 0x85, 0xe0, 0x96, 0x57, 0x63,
	0x74, 0x23, 0x8d, 0xcd, 0x92, 0x65, 0xbc, 0xda, 0xfb, 0xfa, 0xf0, 0xf8, 0x84, 0x5b, 0x1e, 0x0a,
	0x28, 0x7c, 0xc9, 0xe5, 0x4c, 0x6c, 0xb0, 0x1f, 0xa5, 0xb1, 0xec, 0x2b, 0x38, 0x1a, 0xef, 0xb6,
	0x68, 0x0c, 0xbf, 0xc0, 0xea, 0x92, 0x9b, 0x4b, 0x7a, 0x23, 0x69, 0xc9, 0x82, 0xef, 0x27, 0xef,
	0x7a, 0xc1, 0xcd, 0x25, 0x7b, 0x0a, 0xfb, 0x1a, 0x4d, 0xaf, 0x3a, 0x83, 0x9e, 0x6e, 0x4a, 0x74,
	0xf3, 0xe3, 0x32, 0xa0, 0x23, 0xd7, 0xdd, 0x31, 0x8c, 0x88, 0xee, 0x43, 0x52, 0x37, 0xca, 0xa0,
	0xc8, 0xd2, 0x65, 0xb4, 0x9a, 0x96, 0xc1, 0x72, 0x2f, 0xdc, 0x95, 0x28, 0x2a, 0x57, 0x24, 0x90,
	0x6b, 0x4a, 0xc0, 0xcf, 0x83, 0x65, 0x2b, 0x98, 0xd7, 0xbc, 0xab, 0xb8, 0x10, 0x15, 0xaf, 0x6b,
	0x34, 0x46, 0xe9, 0x6c, 0x8f, 0x62, 0x0e, 0x6a, 0xde, 0xad, 0x85, 0x58, 0x07, 0xd4, 0x89, 0x5e,
	0x5d, 0x77, 0xa8, 0xb3, 0xbb, 0xf4, 0xc7, 0xbd, 0xe1, 0xf4, 0xdd, 0x2a, 0x81, 0xd9, 0x3e, 0x35,
	0x8f, 0xce, 0xf9, 0x9f, 0x11, 0xb0, 0x7f, 0x77, 0xc6, 0x0d, 0xd7, 0xa0, 0xbe, 0x92, 0xf5, 0x2d,
	0x3d, 0xa4, 0x01, 0x29, 0x04, 0x7b, 0x04, 0xc0, 0x4d, 0x25, 0x85, 0x2f, 0x79, 0x67, 0x19, 0xbb,
	0x4d, 0xc4, 0x4d, 0x21, 0xa8, 0xb8, 0x7b, 0x90, 0xd0, 0x84, 0x0d, 0x0d, 0x38, 0x2e, 0x27, 0x6e,
	0xc0, 0x86, 0x1d, 0xc3, 0xe1, 0xd8, 0x5c, 0xda, 0xe1, 0xc6, 0xf7, 0xd6, 0xef, 0xb1, 0x85, 0xbe,
	0xa5, 0x2d, 0x43, 0xad, 0xfd, 0x02, 0x0e, 0x79, 0x67, 0xae, 0x51, 0xa3, 0xa8, 0x6e, 0xb1, 0x4d,
	0x88, 0x6d, 0x3e, 0xba, 0xd6, 0x23, 0xeb, 0x53, 0x78, 0xa0, 0xb1, 0x46, 0x79, 0x85, 0xa2, 0x22,
	0x15, 0x9c, 0x6b, 0xd5, 0x6e, 0x24, 0x90, 0x96, 0x47, 0xa3, 0xdb, 0xd5, 0xfb, 0x4c, 0xab, 0xd6,
	0x5d, 0xcb, 0xff, 0xd8, 0x81, 0xd9, 0x3f, 0x66, 0xc5, 0xe6, 0x10, 0x3b, 0x15, 0x46, 0xa4, 0x42,
	0x77, 0x74, 0x88, 0x13, 0xac, 0x7f, 0x46, 0xee, 0xe8, 0x26, 0x68, 0x2c, 0xb7, 0x83, 0x09, 0xcb,
	0x3a, 0x58, 0xec, 0x11, 0xa4, 0x46, 0x5e, 0x74, 0xdc, 0x0e, 0x7a, 0xdc, 0xd1, 0x1b, 0x80, 0x7d,
	0x06, 0x07, 0x52, 0x60, 0x67, 0xa5, 0xbd, 0xa9, 0x7a, 0xad, 0xd4, 0x79, 0x58, 0xd7, 0xfb, 0x23,
	0x7a, 0xe6, 0x40, 0xf6, 0x04, 0x58, 0xaf, 0xe5, 0x15, 0xb7, 0xe8, 0xa3, 0x7c, 0xa7, 0x12, 0x0a,
	0x9d, 0x07, 0x0f, 0x45, 0x52, 0xa3, 0xee, 0x41, 0x22, 0x45, 0xef, 0x06, 0xe5, 0x75, 0x3a, 0x91,
	0xa2, 0x2f, 0x04, 0xfb, 0x14, 0xf6, 0xae, 0xdc, 0xa6, 0x0d, 0x44, 0x53, 0xf2, 0x01, 0x41, 0x9e,
	0xe5, 0x21, 0xa4, 0x3e, 0xc0, 0x15, 0x9b, 0xfa, 0xcf, 0x09, 0x01, 0xe1, 0xd1, 0x79, 0xe7, 0xa6,
	0x1a, 0xa0, 0x90, 0x03, 0x82, 0x5f, 0x8e, 0xe8, 0xeb, 0x84, 0x3e, 0xc5, 0xdf, 0xfc, 0x15, 0x00,
	0x00, 0xff, 0xff, 0xb2, 0x81, 0x7a, 0xb3, 0xa6, 0x07, 0x00, 0x00,
}
