// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/param/param.proto

package param

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitNDIDParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitNDIDParam) Reset()         { *m = InitNDIDParam{} }
func (m *InitNDIDParam) String() string { return proto.CompactTextString(m) }
func (*InitNDIDParam) ProtoMessage()    {}
func (*InitNDIDParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_015e4771f11293e2, []int{0}
}
func (m *InitNDIDParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitNDIDParam.Unmarshal(m, b)
}
func (m *InitNDIDParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitNDIDParam.Marshal(b, m, deterministic)
}
func (dst *InitNDIDParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitNDIDParam.Merge(dst, src)
}
func (m *InitNDIDParam) XXX_Size() int {
	return xxx_messageInfo_InitNDIDParam.Size(m)
}
func (m *InitNDIDParam) XXX_DiscardUnknown() {
	xxx_messageInfo_InitNDIDParam.DiscardUnknown(m)
}

var xxx_messageInfo_InitNDIDParam proto.InternalMessageInfo

func (m *InitNDIDParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *InitNDIDParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *InitNDIDParam) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type RegisterNodeParam struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,6,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,7,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeParam) Reset()         { *m = RegisterNodeParam{} }
func (m *RegisterNodeParam) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeParam) ProtoMessage()    {}
func (*RegisterNodeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_015e4771f11293e2, []int{1}
}
func (m *RegisterNodeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeParam.Unmarshal(m, b)
}
func (m *RegisterNodeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeParam.Marshal(b, m, deterministic)
}
func (dst *RegisterNodeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeParam.Merge(dst, src)
}
func (m *RegisterNodeParam) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeParam.Size(m)
}
func (m *RegisterNodeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeParam.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeParam proto.InternalMessageInfo

func (m *RegisterNodeParam) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RegisterNodeParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RegisterNodeParam) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *RegisterNodeParam) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *RegisterNodeParam) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RegisterNodeParam) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *RegisterNodeParam) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

type UpdateNodeParam struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeParam) Reset()         { *m = UpdateNodeParam{} }
func (m *UpdateNodeParam) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeParam) ProtoMessage()    {}
func (*UpdateNodeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_param_015e4771f11293e2, []int{2}
}
func (m *UpdateNodeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeParam.Unmarshal(m, b)
}
func (m *UpdateNodeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeParam.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeParam.Merge(dst, src)
}
func (m *UpdateNodeParam) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeParam.Size(m)
}
func (m *UpdateNodeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeParam.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeParam proto.InternalMessageInfo

func (m *UpdateNodeParam) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UpdateNodeParam) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func init() {
	proto.RegisterType((*InitNDIDParam)(nil), "InitNDIDParam")
	proto.RegisterType((*RegisterNodeParam)(nil), "RegisterNodeParam")
	proto.RegisterType((*UpdateNodeParam)(nil), "UpdateNodeParam")
}

func init() { proto.RegisterFile("protos/param/param.proto", fileDescriptor_param_015e4771f11293e2) }

var fileDescriptor_param_015e4771f11293e2 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x85, 0x90, 0x7a, 0x60, 0x21, 0xa5, 0x62, 0x2e,
	0x5e, 0xcf, 0xbc, 0xcc, 0x12, 0x3f, 0x17, 0x4f, 0x97, 0x00, 0x90, 0xb0, 0x90, 0x38, 0x17, 0x7b,
	0x5e, 0x7e, 0x4a, 0x6a, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x1b, 0x88,
	0xeb, 0x99, 0x22, 0x24, 0xcb, 0xc5, 0x55, 0x50, 0x9a, 0x94, 0x93, 0x99, 0x1c, 0x9f, 0x9d, 0x5a,
	0x29, 0xc1, 0x04, 0x96, 0xe3, 0x84, 0x88, 0x78, 0xa7, 0x56, 0x0a, 0x69, 0x71, 0x09, 0xe6, 0x26,
	0x16, 0x97, 0xa4, 0x16, 0xc5, 0x23, 0xa9, 0x62, 0x06, 0xab, 0xe2, 0x87, 0x48, 0x04, 0xc0, 0xd4,
	0x2a, 0xdd, 0x62, 0xe4, 0x12, 0x0c, 0x4a, 0x4d, 0xcf, 0x04, 0x89, 0xfa, 0xe5, 0xa7, 0xa4, 0xd2,
	0xcd, 0x66, 0x21, 0x69, 0x2e, 0x4e, 0xb0, 0x1d, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x2c, 0x60, 0x35,
	0x1c, 0x20, 0x01, 0xbf, 0xc4, 0xdc, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xa2, 0xfc, 0x9c, 0x54, 0x09,
	0x56, 0xb0, 0x38, 0x98, 0x0d, 0x72, 0x54, 0x6e, 0x62, 0x45, 0x7c, 0x66, 0x62, 0x8e, 0x04, 0x9b,
	0x02, 0xa3, 0x06, 0x63, 0x10, 0x5b, 0x6e, 0x62, 0x85, 0x67, 0x62, 0x0e, 0x4c, 0x22, 0x31, 0x31,
	0x47, 0x82, 0x1d, 0x2e, 0xe1, 0x98, 0x98, 0xa3, 0x14, 0xc3, 0xc5, 0x1f, 0x5a, 0x90, 0x92, 0x58,
	0x92, 0x8a, 0xf0, 0x19, 0xaa, 0x07, 0x18, 0x89, 0xf2, 0x00, 0x13, 0x56, 0x0f, 0x24, 0xb1, 0x81,
	0xa3, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x34, 0xf4, 0xc5, 0x3e, 0xd2, 0x01, 0x00, 0x00,
}
