// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/params/params.proto

package params

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitNDIDParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitNDIDParams) Reset()         { *m = InitNDIDParams{} }
func (m *InitNDIDParams) String() string { return proto.CompactTextString(m) }
func (*InitNDIDParams) ProtoMessage()    {}
func (*InitNDIDParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{0}
}
func (m *InitNDIDParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitNDIDParams.Unmarshal(m, b)
}
func (m *InitNDIDParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitNDIDParams.Marshal(b, m, deterministic)
}
func (dst *InitNDIDParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitNDIDParams.Merge(dst, src)
}
func (m *InitNDIDParams) XXX_Size() int {
	return xxx_messageInfo_InitNDIDParams.Size(m)
}
func (m *InitNDIDParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InitNDIDParams.DiscardUnknown(m)
}

var xxx_messageInfo_InitNDIDParams proto.InternalMessageInfo

func (m *InitNDIDParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *InitNDIDParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *InitNDIDParams) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type RegisterNodeParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,6,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,7,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeParams) Reset()         { *m = RegisterNodeParams{} }
func (m *RegisterNodeParams) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeParams) ProtoMessage()    {}
func (*RegisterNodeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{1}
}
func (m *RegisterNodeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeParams.Unmarshal(m, b)
}
func (m *RegisterNodeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeParams.Marshal(b, m, deterministic)
}
func (dst *RegisterNodeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeParams.Merge(dst, src)
}
func (m *RegisterNodeParams) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeParams.Size(m)
}
func (m *RegisterNodeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeParams proto.InternalMessageInfo

func (m *RegisterNodeParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RegisterNodeParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RegisterNodeParams) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *RegisterNodeParams) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *RegisterNodeParams) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RegisterNodeParams) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *RegisterNodeParams) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

type UpdateNodeParams struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeParams) Reset()         { *m = UpdateNodeParams{} }
func (m *UpdateNodeParams) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeParams) ProtoMessage()    {}
func (*UpdateNodeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{2}
}
func (m *UpdateNodeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeParams.Unmarshal(m, b)
}
func (m *UpdateNodeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeParams.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeParams.Merge(dst, src)
}
func (m *UpdateNodeParams) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeParams.Size(m)
}
func (m *UpdateNodeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeParams proto.InternalMessageInfo

func (m *UpdateNodeParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UpdateNodeParams) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type SetValidatorParams struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Power                int64    `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValidatorParams) Reset()         { *m = SetValidatorParams{} }
func (m *SetValidatorParams) String() string { return proto.CompactTextString(m) }
func (*SetValidatorParams) ProtoMessage()    {}
func (*SetValidatorParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{3}
}
func (m *SetValidatorParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValidatorParams.Unmarshal(m, b)
}
func (m *SetValidatorParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValidatorParams.Marshal(b, m, deterministic)
}
func (dst *SetValidatorParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValidatorParams.Merge(dst, src)
}
func (m *SetValidatorParams) XXX_Size() int {
	return xxx_messageInfo_SetValidatorParams.Size(m)
}
func (m *SetValidatorParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValidatorParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetValidatorParams proto.InternalMessageInfo

func (m *SetValidatorParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SetValidatorParams) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type SetPriceFuncParams struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPriceFuncParams) Reset()         { *m = SetPriceFuncParams{} }
func (m *SetPriceFuncParams) String() string { return proto.CompactTextString(m) }
func (*SetPriceFuncParams) ProtoMessage()    {}
func (*SetPriceFuncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{4}
}
func (m *SetPriceFuncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPriceFuncParams.Unmarshal(m, b)
}
func (m *SetPriceFuncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPriceFuncParams.Marshal(b, m, deterministic)
}
func (dst *SetPriceFuncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPriceFuncParams.Merge(dst, src)
}
func (m *SetPriceFuncParams) XXX_Size() int {
	return xxx_messageInfo_SetPriceFuncParams.Size(m)
}
func (m *SetPriceFuncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPriceFuncParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetPriceFuncParams proto.InternalMessageInfo

func (m *SetPriceFuncParams) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *SetPriceFuncParams) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetPriceFuncParams struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceFuncParams) Reset()         { *m = GetPriceFuncParams{} }
func (m *GetPriceFuncParams) String() string { return proto.CompactTextString(m) }
func (*GetPriceFuncParams) ProtoMessage()    {}
func (*GetPriceFuncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{5}
}
func (m *GetPriceFuncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceFuncParams.Unmarshal(m, b)
}
func (m *GetPriceFuncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceFuncParams.Marshal(b, m, deterministic)
}
func (dst *GetPriceFuncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceFuncParams.Merge(dst, src)
}
func (m *GetPriceFuncParams) XXX_Size() int {
	return xxx_messageInfo_GetPriceFuncParams.Size(m)
}
func (m *GetPriceFuncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceFuncParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceFuncParams proto.InternalMessageInfo

func (m *GetPriceFuncParams) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type SetNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodeTokenParams) Reset()         { *m = SetNodeTokenParams{} }
func (m *SetNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*SetNodeTokenParams) ProtoMessage()    {}
func (*SetNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{6}
}
func (m *SetNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodeTokenParams.Unmarshal(m, b)
}
func (m *SetNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *SetNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodeTokenParams.Merge(dst, src)
}
func (m *SetNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_SetNodeTokenParams.Size(m)
}
func (m *SetNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodeTokenParams proto.InternalMessageInfo

func (m *SetNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SetNodeTokenParams) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type AddNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeTokenParams) Reset()         { *m = AddNodeTokenParams{} }
func (m *AddNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*AddNodeTokenParams) ProtoMessage()    {}
func (*AddNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{7}
}
func (m *AddNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeTokenParams.Unmarshal(m, b)
}
func (m *AddNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *AddNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeTokenParams.Merge(dst, src)
}
func (m *AddNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_AddNodeTokenParams.Size(m)
}
func (m *AddNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeTokenParams proto.InternalMessageInfo

func (m *AddNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddNodeTokenParams) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReduceNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceNodeTokenParams) Reset()         { *m = ReduceNodeTokenParams{} }
func (m *ReduceNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*ReduceNodeTokenParams) ProtoMessage()    {}
func (*ReduceNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{8}
}
func (m *ReduceNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceNodeTokenParams.Unmarshal(m, b)
}
func (m *ReduceNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *ReduceNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceNodeTokenParams.Merge(dst, src)
}
func (m *ReduceNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_ReduceNodeTokenParams.Size(m)
}
func (m *ReduceNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceNodeTokenParams proto.InternalMessageInfo

func (m *ReduceNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ReduceNodeTokenParams) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GetNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeTokenParams) Reset()         { *m = GetNodeTokenParams{} }
func (m *GetNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*GetNodeTokenParams) ProtoMessage()    {}
func (*GetNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{9}
}
func (m *GetNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeTokenParams.Unmarshal(m, b)
}
func (m *GetNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *GetNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeTokenParams.Merge(dst, src)
}
func (m *GetNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_GetNodeTokenParams.Size(m)
}
func (m *GetNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeTokenParams proto.InternalMessageInfo

func (m *GetNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type CreateRequestParams struct {
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64                  `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64                `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64                `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64                  `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	DataRequestList      []*DataRequestInParams `protobuf:"bytes,6,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string                 `protobuf:"bytes,7,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	Mode                 int64                  `protobuf:"varint,13,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateRequestParams) Reset()         { *m = CreateRequestParams{} }
func (m *CreateRequestParams) String() string { return proto.CompactTextString(m) }
func (*CreateRequestParams) ProtoMessage()    {}
func (*CreateRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{10}
}
func (m *CreateRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestParams.Unmarshal(m, b)
}
func (m *CreateRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestParams.Marshal(b, m, deterministic)
}
func (dst *CreateRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestParams.Merge(dst, src)
}
func (m *CreateRequestParams) XXX_Size() int {
	return xxx_messageInfo_CreateRequestParams.Size(m)
}
func (m *CreateRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestParams proto.InternalMessageInfo

func (m *CreateRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateRequestParams) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *CreateRequestParams) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *CreateRequestParams) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *CreateRequestParams) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *CreateRequestParams) GetDataRequestList() []*DataRequestInParams {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *CreateRequestParams) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *CreateRequestParams) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type DataRequestInParams struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	Request_ParamsHash   string   `protobuf:"bytes,4,opt,name=request_Params_hash,json=requestParamsHash,proto3" json:"request_Params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequestInParams) Reset()         { *m = DataRequestInParams{} }
func (m *DataRequestInParams) String() string { return proto.CompactTextString(m) }
func (*DataRequestInParams) ProtoMessage()    {}
func (*DataRequestInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{11}
}
func (m *DataRequestInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequestInParams.Unmarshal(m, b)
}
func (m *DataRequestInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequestInParams.Marshal(b, m, deterministic)
}
func (dst *DataRequestInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequestInParams.Merge(dst, src)
}
func (m *DataRequestInParams) XXX_Size() int {
	return xxx_messageInfo_DataRequestInParams.Size(m)
}
func (m *DataRequestInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequestInParams.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequestInParams proto.InternalMessageInfo

func (m *DataRequestInParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequestInParams) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequestInParams) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequestInParams) GetRequest_ParamsHash() string {
	if m != nil {
		return m.Request_ParamsHash
	}
	return ""
}

func (m *DataRequestInParams) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequestInParams) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type CloseRequestParams struct {
	RequestId            string           `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseValidList    []*ResponseValid `protobuf:"bytes,2,rep,name=response_valid_list,json=responseValidList,proto3" json:"response_valid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CloseRequestParams) Reset()         { *m = CloseRequestParams{} }
func (m *CloseRequestParams) String() string { return proto.CompactTextString(m) }
func (*CloseRequestParams) ProtoMessage()    {}
func (*CloseRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{12}
}
func (m *CloseRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequestParams.Unmarshal(m, b)
}
func (m *CloseRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequestParams.Marshal(b, m, deterministic)
}
func (dst *CloseRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequestParams.Merge(dst, src)
}
func (m *CloseRequestParams) XXX_Size() int {
	return xxx_messageInfo_CloseRequestParams.Size(m)
}
func (m *CloseRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequestParams proto.InternalMessageInfo

func (m *CloseRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CloseRequestParams) GetResponseValidList() []*ResponseValid {
	if m != nil {
		return m.ResponseValidList
	}
	return nil
}

type TimeOutRequestParams struct {
	RequestId            string           `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseValidList    []*ResponseValid `protobuf:"bytes,2,rep,name=response_valid_list,json=responseValidList,proto3" json:"response_valid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TimeOutRequestParams) Reset()         { *m = TimeOutRequestParams{} }
func (m *TimeOutRequestParams) String() string { return proto.CompactTextString(m) }
func (*TimeOutRequestParams) ProtoMessage()    {}
func (*TimeOutRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{13}
}
func (m *TimeOutRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOutRequestParams.Unmarshal(m, b)
}
func (m *TimeOutRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOutRequestParams.Marshal(b, m, deterministic)
}
func (dst *TimeOutRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOutRequestParams.Merge(dst, src)
}
func (m *TimeOutRequestParams) XXX_Size() int {
	return xxx_messageInfo_TimeOutRequestParams.Size(m)
}
func (m *TimeOutRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOutRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOutRequestParams proto.InternalMessageInfo

func (m *TimeOutRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *TimeOutRequestParams) GetResponseValidList() []*ResponseValid {
	if m != nil {
		return m.ResponseValidList
	}
	return nil
}

type ResponseValid struct {
	IdpId string `protobuf:"bytes,1,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	// Types that are valid to be assigned to ValidProof:
	//	*ResponseValid_ValidProofBool
	ValidProof isResponseValid_ValidProof `protobuf_oneof:"valid_proof"`
	// Types that are valid to be assigned to ValidIal:
	//	*ResponseValid_ValidIalBool
	ValidIal isResponseValid_ValidIal `protobuf_oneof:"valid_ial"`
	// Types that are valid to be assigned to ValidSignature:
	//	*ResponseValid_ValidSignatureBool
	ValidSignature       isResponseValid_ValidSignature `protobuf_oneof:"valid_signature"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ResponseValid) Reset()         { *m = ResponseValid{} }
func (m *ResponseValid) String() string { return proto.CompactTextString(m) }
func (*ResponseValid) ProtoMessage()    {}
func (*ResponseValid) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{14}
}
func (m *ResponseValid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseValid.Unmarshal(m, b)
}
func (m *ResponseValid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseValid.Marshal(b, m, deterministic)
}
func (dst *ResponseValid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseValid.Merge(dst, src)
}
func (m *ResponseValid) XXX_Size() int {
	return xxx_messageInfo_ResponseValid.Size(m)
}
func (m *ResponseValid) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseValid.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseValid proto.InternalMessageInfo

func (m *ResponseValid) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

type isResponseValid_ValidProof interface {
	isResponseValid_ValidProof()
}

type ResponseValid_ValidProofBool struct {
	ValidProofBool bool `protobuf:"varint,2,opt,name=valid_proof_bool,json=validProofBool,proto3,oneof"`
}

func (*ResponseValid_ValidProofBool) isResponseValid_ValidProof() {}

func (m *ResponseValid) GetValidProof() isResponseValid_ValidProof {
	if m != nil {
		return m.ValidProof
	}
	return nil
}

func (m *ResponseValid) GetValidProofBool() bool {
	if x, ok := m.GetValidProof().(*ResponseValid_ValidProofBool); ok {
		return x.ValidProofBool
	}
	return false
}

type isResponseValid_ValidIal interface {
	isResponseValid_ValidIal()
}

type ResponseValid_ValidIalBool struct {
	ValidIalBool bool `protobuf:"varint,3,opt,name=valid_ial_bool,json=validIalBool,proto3,oneof"`
}

func (*ResponseValid_ValidIalBool) isResponseValid_ValidIal() {}

func (m *ResponseValid) GetValidIal() isResponseValid_ValidIal {
	if m != nil {
		return m.ValidIal
	}
	return nil
}

func (m *ResponseValid) GetValidIalBool() bool {
	if x, ok := m.GetValidIal().(*ResponseValid_ValidIalBool); ok {
		return x.ValidIalBool
	}
	return false
}

type isResponseValid_ValidSignature interface {
	isResponseValid_ValidSignature()
}

type ResponseValid_ValidSignatureBool struct {
	ValidSignatureBool bool `protobuf:"varint,4,opt,name=valid_signature_bool,json=validSignatureBool,proto3,oneof"`
}

func (*ResponseValid_ValidSignatureBool) isResponseValid_ValidSignature() {}

func (m *ResponseValid) GetValidSignature() isResponseValid_ValidSignature {
	if m != nil {
		return m.ValidSignature
	}
	return nil
}

func (m *ResponseValid) GetValidSignatureBool() bool {
	if x, ok := m.GetValidSignature().(*ResponseValid_ValidSignatureBool); ok {
		return x.ValidSignatureBool
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResponseValid) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResponseValid_OneofMarshaler, _ResponseValid_OneofUnmarshaler, _ResponseValid_OneofSizer, []interface{}{
		(*ResponseValid_ValidProofBool)(nil),
		(*ResponseValid_ValidIalBool)(nil),
		(*ResponseValid_ValidSignatureBool)(nil),
	}
}

func _ResponseValid_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResponseValid)
	// valid_proof
	switch x := m.ValidProof.(type) {
	case *ResponseValid_ValidProofBool:
		t := uint64(0)
		if x.ValidProofBool {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ResponseValid.ValidProof has unexpected type %T", x)
	}
	// valid_ial
	switch x := m.ValidIal.(type) {
	case *ResponseValid_ValidIalBool:
		t := uint64(0)
		if x.ValidIalBool {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ResponseValid.ValidIal has unexpected type %T", x)
	}
	// valid_signature
	switch x := m.ValidSignature.(type) {
	case *ResponseValid_ValidSignatureBool:
		t := uint64(0)
		if x.ValidSignatureBool {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ResponseValid.ValidSignature has unexpected type %T", x)
	}
	return nil
}

func _ResponseValid_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResponseValid)
	switch tag {
	case 2: // valid_proof.valid_proof_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ValidProof = &ResponseValid_ValidProofBool{x != 0}
		return true, err
	case 3: // valid_ial.valid_ial_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ValidIal = &ResponseValid_ValidIalBool{x != 0}
		return true, err
	case 4: // valid_signature.valid_signature_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ValidSignature = &ResponseValid_ValidSignatureBool{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _ResponseValid_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResponseValid)
	// valid_proof
	switch x := m.ValidProof.(type) {
	case *ResponseValid_ValidProofBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// valid_ial
	switch x := m.ValidIal.(type) {
	case *ResponseValid_ValidIalBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// valid_signature
	switch x := m.ValidSignature.(type) {
	case *ResponseValid_ValidSignatureBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetDataReceivedParams struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsId                 string   `protobuf:"bytes,3,opt,name=as_id,json=asId,proto3" json:"as_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataReceivedParams) Reset()         { *m = SetDataReceivedParams{} }
func (m *SetDataReceivedParams) String() string { return proto.CompactTextString(m) }
func (*SetDataReceivedParams) ProtoMessage()    {}
func (*SetDataReceivedParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{15}
}
func (m *SetDataReceivedParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataReceivedParams.Unmarshal(m, b)
}
func (m *SetDataReceivedParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataReceivedParams.Marshal(b, m, deterministic)
}
func (dst *SetDataReceivedParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataReceivedParams.Merge(dst, src)
}
func (m *SetDataReceivedParams) XXX_Size() int {
	return xxx_messageInfo_SetDataReceivedParams.Size(m)
}
func (m *SetDataReceivedParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataReceivedParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataReceivedParams proto.InternalMessageInfo

func (m *SetDataReceivedParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SetDataReceivedParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *SetDataReceivedParams) GetAsId() string {
	if m != nil {
		return m.AsId
	}
	return ""
}

type SignDataParams struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	RequestId            string   `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDataParams) Reset()         { *m = SignDataParams{} }
func (m *SignDataParams) String() string { return proto.CompactTextString(m) }
func (*SignDataParams) ProtoMessage()    {}
func (*SignDataParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{16}
}
func (m *SignDataParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDataParams.Unmarshal(m, b)
}
func (m *SignDataParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDataParams.Marshal(b, m, deterministic)
}
func (dst *SignDataParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDataParams.Merge(dst, src)
}
func (m *SignDataParams) XXX_Size() int {
	return xxx_messageInfo_SignDataParams.Size(m)
}
func (m *SignDataParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDataParams.DiscardUnknown(m)
}

var xxx_messageInfo_SignDataParams proto.InternalMessageInfo

func (m *SignDataParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *SignDataParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SignDataParams) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type RegisterServiceDestinationParams struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MinIal               float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal               float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServiceDestinationParams) Reset()         { *m = RegisterServiceDestinationParams{} }
func (m *RegisterServiceDestinationParams) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceDestinationParams) ProtoMessage()    {}
func (*RegisterServiceDestinationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{17}
}
func (m *RegisterServiceDestinationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceDestinationParams.Unmarshal(m, b)
}
func (m *RegisterServiceDestinationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceDestinationParams.Marshal(b, m, deterministic)
}
func (dst *RegisterServiceDestinationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceDestinationParams.Merge(dst, src)
}
func (m *RegisterServiceDestinationParams) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceDestinationParams.Size(m)
}
func (m *RegisterServiceDestinationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceDestinationParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceDestinationParams proto.InternalMessageInfo

func (m *RegisterServiceDestinationParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *RegisterServiceDestinationParams) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *RegisterServiceDestinationParams) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

type UpdateServiceDestinationParams struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MinIal               float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal               float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceDestinationParams) Reset()         { *m = UpdateServiceDestinationParams{} }
func (m *UpdateServiceDestinationParams) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceDestinationParams) ProtoMessage()    {}
func (*UpdateServiceDestinationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{18}
}
func (m *UpdateServiceDestinationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceDestinationParams.Unmarshal(m, b)
}
func (m *UpdateServiceDestinationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceDestinationParams.Marshal(b, m, deterministic)
}
func (dst *UpdateServiceDestinationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceDestinationParams.Merge(dst, src)
}
func (m *UpdateServiceDestinationParams) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceDestinationParams.Size(m)
}
func (m *UpdateServiceDestinationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceDestinationParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceDestinationParams proto.InternalMessageInfo

func (m *UpdateServiceDestinationParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *UpdateServiceDestinationParams) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *UpdateServiceDestinationParams) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

type DisableServiceDestinationParams struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableServiceDestinationParams) Reset()         { *m = DisableServiceDestinationParams{} }
func (m *DisableServiceDestinationParams) String() string { return proto.CompactTextString(m) }
func (*DisableServiceDestinationParams) ProtoMessage()    {}
func (*DisableServiceDestinationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{19}
}
func (m *DisableServiceDestinationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableServiceDestinationParams.Unmarshal(m, b)
}
func (m *DisableServiceDestinationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableServiceDestinationParams.Marshal(b, m, deterministic)
}
func (dst *DisableServiceDestinationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableServiceDestinationParams.Merge(dst, src)
}
func (m *DisableServiceDestinationParams) XXX_Size() int {
	return xxx_messageInfo_DisableServiceDestinationParams.Size(m)
}
func (m *DisableServiceDestinationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableServiceDestinationParams.DiscardUnknown(m)
}

var xxx_messageInfo_DisableServiceDestinationParams proto.InternalMessageInfo

func (m *DisableServiceDestinationParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type GetUsedTokenReportParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsedTokenReportParams) Reset()         { *m = GetUsedTokenReportParams{} }
func (m *GetUsedTokenReportParams) String() string { return proto.CompactTextString(m) }
func (*GetUsedTokenReportParams) ProtoMessage()    {}
func (*GetUsedTokenReportParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{20}
}
func (m *GetUsedTokenReportParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsedTokenReportParams.Unmarshal(m, b)
}
func (m *GetUsedTokenReportParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsedTokenReportParams.Marshal(b, m, deterministic)
}
func (dst *GetUsedTokenReportParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsedTokenReportParams.Merge(dst, src)
}
func (m *GetUsedTokenReportParams) XXX_Size() int {
	return xxx_messageInfo_GetUsedTokenReportParams.Size(m)
}
func (m *GetUsedTokenReportParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsedTokenReportParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsedTokenReportParams proto.InternalMessageInfo

func (m *GetUsedTokenReportParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type CreateIdentityParams struct {
	AccessorId           string   `protobuf:"bytes,1,opt,name=accessor_id,json=accessorId,proto3" json:"accessor_id,omitempty"`
	AccessorType         string   `protobuf:"bytes,2,opt,name=accessor_type,json=accessorType,proto3" json:"accessor_type,omitempty"`
	AccessorPublicKey    string   `protobuf:"bytes,3,opt,name=accessor_public_key,json=accessorPublicKey,proto3" json:"accessor_public_key,omitempty"`
	AccessorGroupId      string   `protobuf:"bytes,4,opt,name=accessor_group_id,json=accessorGroupId,proto3" json:"accessor_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIdentityParams) Reset()         { *m = CreateIdentityParams{} }
func (m *CreateIdentityParams) String() string { return proto.CompactTextString(m) }
func (*CreateIdentityParams) ProtoMessage()    {}
func (*CreateIdentityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{21}
}
func (m *CreateIdentityParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIdentityParams.Unmarshal(m, b)
}
func (m *CreateIdentityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIdentityParams.Marshal(b, m, deterministic)
}
func (dst *CreateIdentityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIdentityParams.Merge(dst, src)
}
func (m *CreateIdentityParams) XXX_Size() int {
	return xxx_messageInfo_CreateIdentityParams.Size(m)
}
func (m *CreateIdentityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIdentityParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIdentityParams proto.InternalMessageInfo

func (m *CreateIdentityParams) GetAccessorId() string {
	if m != nil {
		return m.AccessorId
	}
	return ""
}

func (m *CreateIdentityParams) GetAccessorType() string {
	if m != nil {
		return m.AccessorType
	}
	return ""
}

func (m *CreateIdentityParams) GetAccessorPublicKey() string {
	if m != nil {
		return m.AccessorPublicKey
	}
	return ""
}

func (m *CreateIdentityParams) GetAccessorGroupId() string {
	if m != nil {
		return m.AccessorGroupId
	}
	return ""
}

type AccessorMethodParams struct {
	AccessorId           string   `protobuf:"bytes,1,opt,name=accessor_id,json=accessorId,proto3" json:"accessor_id,omitempty"`
	AccessorType         string   `protobuf:"bytes,2,opt,name=accessor_type,json=accessorType,proto3" json:"accessor_type,omitempty"`
	AccessorPublicKey    string   `protobuf:"bytes,3,opt,name=accessor_public_key,json=accessorPublicKey,proto3" json:"accessor_public_key,omitempty"`
	AccessorGroupId      string   `protobuf:"bytes,4,opt,name=accessor_group_id,json=accessorGroupId,proto3" json:"accessor_group_id,omitempty"`
	RequestId            string   `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessorMethodParams) Reset()         { *m = AccessorMethodParams{} }
func (m *AccessorMethodParams) String() string { return proto.CompactTextString(m) }
func (*AccessorMethodParams) ProtoMessage()    {}
func (*AccessorMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{22}
}
func (m *AccessorMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessorMethodParams.Unmarshal(m, b)
}
func (m *AccessorMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessorMethodParams.Marshal(b, m, deterministic)
}
func (dst *AccessorMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessorMethodParams.Merge(dst, src)
}
func (m *AccessorMethodParams) XXX_Size() int {
	return xxx_messageInfo_AccessorMethodParams.Size(m)
}
func (m *AccessorMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessorMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_AccessorMethodParams proto.InternalMessageInfo

func (m *AccessorMethodParams) GetAccessorId() string {
	if m != nil {
		return m.AccessorId
	}
	return ""
}

func (m *AccessorMethodParams) GetAccessorType() string {
	if m != nil {
		return m.AccessorType
	}
	return ""
}

func (m *AccessorMethodParams) GetAccessorPublicKey() string {
	if m != nil {
		return m.AccessorPublicKey
	}
	return ""
}

func (m *AccessorMethodParams) GetAccessorGroupId() string {
	if m != nil {
		return m.AccessorGroupId
	}
	return ""
}

func (m *AccessorMethodParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type ClearRegisterMsqDestinationTimeoutParams struct {
	HashId               string   `protobuf:"bytes,1,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRegisterMsqDestinationTimeoutParams) Reset() {
	*m = ClearRegisterMsqDestinationTimeoutParams{}
}
func (m *ClearRegisterMsqDestinationTimeoutParams) String() string { return proto.CompactTextString(m) }
func (*ClearRegisterMsqDestinationTimeoutParams) ProtoMessage()    {}
func (*ClearRegisterMsqDestinationTimeoutParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{23}
}
func (m *ClearRegisterMsqDestinationTimeoutParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRegisterMsqDestinationTimeoutParams.Unmarshal(m, b)
}
func (m *ClearRegisterMsqDestinationTimeoutParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRegisterMsqDestinationTimeoutParams.Marshal(b, m, deterministic)
}
func (dst *ClearRegisterMsqDestinationTimeoutParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRegisterMsqDestinationTimeoutParams.Merge(dst, src)
}
func (m *ClearRegisterMsqDestinationTimeoutParams) XXX_Size() int {
	return xxx_messageInfo_ClearRegisterMsqDestinationTimeoutParams.Size(m)
}
func (m *ClearRegisterMsqDestinationTimeoutParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRegisterMsqDestinationTimeoutParams.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRegisterMsqDestinationTimeoutParams proto.InternalMessageInfo

func (m *ClearRegisterMsqDestinationTimeoutParams) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

type DeclareIdentityProofParams struct {
	IdentityProof        string   `protobuf:"bytes,1,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	RequestId            string   `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeclareIdentityProofParams) Reset()         { *m = DeclareIdentityProofParams{} }
func (m *DeclareIdentityProofParams) String() string { return proto.CompactTextString(m) }
func (*DeclareIdentityProofParams) ProtoMessage()    {}
func (*DeclareIdentityProofParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{24}
}
func (m *DeclareIdentityProofParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeclareIdentityProofParams.Unmarshal(m, b)
}
func (m *DeclareIdentityProofParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeclareIdentityProofParams.Marshal(b, m, deterministic)
}
func (dst *DeclareIdentityProofParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeclareIdentityProofParams.Merge(dst, src)
}
func (m *DeclareIdentityProofParams) XXX_Size() int {
	return xxx_messageInfo_DeclareIdentityProofParams.Size(m)
}
func (m *DeclareIdentityProofParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeclareIdentityProofParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeclareIdentityProofParams proto.InternalMessageInfo

func (m *DeclareIdentityProofParams) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *DeclareIdentityProofParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type UpdateIdentityParams struct {
	HashId               string   `protobuf:"bytes,1,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	Ial                  float64  `protobuf:"fixed64,2,opt,name=ial,proto3" json:"ial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIdentityParams) Reset()         { *m = UpdateIdentityParams{} }
func (m *UpdateIdentityParams) String() string { return proto.CompactTextString(m) }
func (*UpdateIdentityParams) ProtoMessage()    {}
func (*UpdateIdentityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{25}
}
func (m *UpdateIdentityParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIdentityParams.Unmarshal(m, b)
}
func (m *UpdateIdentityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIdentityParams.Marshal(b, m, deterministic)
}
func (dst *UpdateIdentityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIdentityParams.Merge(dst, src)
}
func (m *UpdateIdentityParams) XXX_Size() int {
	return xxx_messageInfo_UpdateIdentityParams.Size(m)
}
func (m *UpdateIdentityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIdentityParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIdentityParams proto.InternalMessageInfo

func (m *UpdateIdentityParams) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *UpdateIdentityParams) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

type CreateIdpResponseParams struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ial                  float64  `protobuf:"fixed64,2,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,3,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityProof        string   `protobuf:"bytes,6,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	PrivateProofHash     string   `protobuf:"bytes,7,opt,name=private_proof_hash,json=privateProofHash,proto3" json:"private_proof_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIdpResponseParams) Reset()         { *m = CreateIdpResponseParams{} }
func (m *CreateIdpResponseParams) String() string { return proto.CompactTextString(m) }
func (*CreateIdpResponseParams) ProtoMessage()    {}
func (*CreateIdpResponseParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{26}
}
func (m *CreateIdpResponseParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIdpResponseParams.Unmarshal(m, b)
}
func (m *CreateIdpResponseParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIdpResponseParams.Marshal(b, m, deterministic)
}
func (dst *CreateIdpResponseParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIdpResponseParams.Merge(dst, src)
}
func (m *CreateIdpResponseParams) XXX_Size() int {
	return xxx_messageInfo_CreateIdpResponseParams.Size(m)
}
func (m *CreateIdpResponseParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIdpResponseParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIdpResponseParams proto.InternalMessageInfo

func (m *CreateIdpResponseParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateIdpResponseParams) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *CreateIdpResponseParams) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *CreateIdpResponseParams) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateIdpResponseParams) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CreateIdpResponseParams) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *CreateIdpResponseParams) GetPrivateProofHash() string {
	if m != nil {
		return m.PrivateProofHash
	}
	return ""
}

type User struct {
	HashId               string   `protobuf:"bytes,1,opt,name=hash_id,json=hashId,proto3" json:"hash_id,omitempty"`
	Ial                  float64  `protobuf:"fixed64,2,opt,name=ial,proto3" json:"ial,omitempty"`
	First                bool     `protobuf:"varint,3,opt,name=first,proto3" json:"first,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{27}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetHashId() string {
	if m != nil {
		return m.HashId
	}
	return ""
}

func (m *User) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *User) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

type RegisterMsqDestinationParams struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterMsqDestinationParams) Reset()         { *m = RegisterMsqDestinationParams{} }
func (m *RegisterMsqDestinationParams) String() string { return proto.CompactTextString(m) }
func (*RegisterMsqDestinationParams) ProtoMessage()    {}
func (*RegisterMsqDestinationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_2087efcd5d73fb16, []int{28}
}
func (m *RegisterMsqDestinationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterMsqDestinationParams.Unmarshal(m, b)
}
func (m *RegisterMsqDestinationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterMsqDestinationParams.Marshal(b, m, deterministic)
}
func (dst *RegisterMsqDestinationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterMsqDestinationParams.Merge(dst, src)
}
func (m *RegisterMsqDestinationParams) XXX_Size() int {
	return xxx_messageInfo_RegisterMsqDestinationParams.Size(m)
}
func (m *RegisterMsqDestinationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterMsqDestinationParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterMsqDestinationParams proto.InternalMessageInfo

func (m *RegisterMsqDestinationParams) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*InitNDIDParams)(nil), "InitNDIDParams")
	proto.RegisterType((*RegisterNodeParams)(nil), "RegisterNodeParams")
	proto.RegisterType((*UpdateNodeParams)(nil), "UpdateNodeParams")
	proto.RegisterType((*SetValidatorParams)(nil), "SetValidatorParams")
	proto.RegisterType((*SetPriceFuncParams)(nil), "SetPriceFuncParams")
	proto.RegisterType((*GetPriceFuncParams)(nil), "GetPriceFuncParams")
	proto.RegisterType((*SetNodeTokenParams)(nil), "SetNodeTokenParams")
	proto.RegisterType((*AddNodeTokenParams)(nil), "AddNodeTokenParams")
	proto.RegisterType((*ReduceNodeTokenParams)(nil), "ReduceNodeTokenParams")
	proto.RegisterType((*GetNodeTokenParams)(nil), "GetNodeTokenParams")
	proto.RegisterType((*CreateRequestParams)(nil), "CreateRequestParams")
	proto.RegisterType((*DataRequestInParams)(nil), "DataRequestInParams")
	proto.RegisterType((*CloseRequestParams)(nil), "CloseRequestParams")
	proto.RegisterType((*TimeOutRequestParams)(nil), "TimeOutRequestParams")
	proto.RegisterType((*ResponseValid)(nil), "ResponseValid")
	proto.RegisterType((*SetDataReceivedParams)(nil), "SetDataReceivedParams")
	proto.RegisterType((*SignDataParams)(nil), "SignDataParams")
	proto.RegisterType((*RegisterServiceDestinationParams)(nil), "RegisterServiceDestinationParams")
	proto.RegisterType((*UpdateServiceDestinationParams)(nil), "UpdateServiceDestinationParams")
	proto.RegisterType((*DisableServiceDestinationParams)(nil), "DisableServiceDestinationParams")
	proto.RegisterType((*GetUsedTokenReportParams)(nil), "GetUsedTokenReportParams")
	proto.RegisterType((*CreateIdentityParams)(nil), "CreateIdentityParams")
	proto.RegisterType((*AccessorMethodParams)(nil), "AccessorMethodParams")
	proto.RegisterType((*ClearRegisterMsqDestinationTimeoutParams)(nil), "ClearRegisterMsqDestinationTimeoutParams")
	proto.RegisterType((*DeclareIdentityProofParams)(nil), "DeclareIdentityProofParams")
	proto.RegisterType((*UpdateIdentityParams)(nil), "UpdateIdentityParams")
	proto.RegisterType((*CreateIdpResponseParams)(nil), "CreateIdpResponseParams")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*RegisterMsqDestinationParams)(nil), "RegisterMsqDestinationParams")
}

func init() { proto.RegisterFile("protos/params/params.proto", fileDescriptor_params_2087efcd5d73fb16) }

var fileDescriptor_params_2087efcd5d73fb16 = []byte{
	// 1155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x5b, 0x6f, 0xdc, 0x44,
	0x14, 0xc6, 0x7b, 0x6b, 0xf7, 0xa4, 0xd9, 0x24, 0xce, 0x96, 0xae, 0xda, 0x42, 0x23, 0x23, 0x20,
	0xaa, 0x68, 0x40, 0xad, 0x78, 0x42, 0xaa, 0xba, 0xc9, 0xd2, 0xc4, 0x82, 0x84, 0xc8, 0x49, 0x78,
	0x43, 0xd6, 0x64, 0xe7, 0x24, 0x19, 0x6a, 0x7b, 0x9c, 0x99, 0x71, 0xda, 0xfc, 0x2b, 0x1e, 0xf9,
	0x27, 0x3c, 0x20, 0x9e, 0xf9, 0x19, 0xa0, 0xb9, 0x78, 0xed, 0xdd, 0xa6, 0xca, 0x96, 0x4a, 0x91,
	0x78, 0x5a, 0xcf, 0x77, 0xae, 0x73, 0xae, 0xb3, 0x70, 0x3f, 0x17, 0x5c, 0x71, 0xf9, 0x75, 0x4e,
	0x04, 0x49, 0xcb, 0x9f, 0x0d, 0x03, 0x06, 0x0a, 0x7a, 0x61, 0xc6, 0xd4, 0xde, 0x28, 0x1c, 0xed,
	0x1b, 0xdc, 0xbf, 0x07, 0xb7, 0x32, 0x4e, 0x31, 0x66, 0x74, 0xe0, 0xad, 0x79, 0xeb, 0xdd, 0xa8,
	0xa3, 0x8f, 0x21, 0xf5, 0x3f, 0x01, 0xc8, 0x8b, 0xe3, 0x84, 0x8d, 0xe3, 0x57, 0x78, 0x39, 0x68,
	0x18, 0x5a, 0xd7, 0x22, 0x3f, 0xe0, 0xa5, 0xff, 0x18, 0x56, 0x52, 0x22, 0x15, 0x8a, 0xb8, 0xc6,
	0xd5, 0x34, 0x5c, 0x4b, 0x96, 0xb0, 0x5f, 0xf2, 0x06, 0x7f, 0x7a, 0xe0, 0x47, 0x78, 0xca, 0x34,
	0xba, 0xc7, 0x29, 0xde, 0x9c, 0x69, 0xff, 0x01, 0x74, 0x8d, 0x8d, 0x8c, 0xa4, 0x38, 0x68, 0x19,
	0x9e, 0xdb, 0x1a, 0xd8, 0x23, 0x29, 0xfa, 0x3e, 0xb4, 0x04, 0x4f, 0x70, 0xd0, 0x36, 0xb8, 0xf9,
	0xd6, 0x4e, 0xa5, 0xe4, 0x4d, 0xcc, 0x48, 0x32, 0xe8, 0xac, 0x79, 0xeb, 0x5e, 0xd4, 0x49, 0xc9,
	0x9b, 0x90, 0x24, 0x25, 0x81, 0x90, 0x64, 0x70, 0x6b, 0x42, 0x18, 0x92, 0x24, 0xf8, 0x05, 0x96,
	0x8f, 0x72, 0x4a, 0x14, 0xd6, 0xae, 0x36, 0x7d, 0x03, 0x6f, 0xae, 0x1b, 0x34, 0xae, 0x0e, 0x5e,
	0x08, 0xfe, 0x01, 0xaa, 0x9f, 0x49, 0xc2, 0x28, 0x51, 0x5c, 0xcc, 0x67, 0xa0, 0x0f, 0xed, 0x9c,
	0xbf, 0x46, 0x61, 0x94, 0x36, 0x23, 0x7b, 0x08, 0x9e, 0x1b, 0x55, 0xfb, 0x82, 0x8d, 0xf1, 0x65,
	0x91, 0x8d, 0x9d, 0x2a, 0x1f, 0x5a, 0x27, 0x45, 0x36, 0x76, 0x4a, 0xcc, 0xb7, 0x91, 0xd7, 0x6c,
	0x46, 0xde, 0x8b, 0xec, 0x21, 0x58, 0x07, 0x7f, 0x7b, 0x2e, 0xf9, 0xe0, 0x7b, 0x63, 0x49, 0x07,
	0xe4, 0x90, 0xbf, 0xc2, 0xec, 0xba, 0x84, 0x7f, 0x0c, 0x1d, 0x92, 0xf2, 0x22, 0x53, 0xce, 0x9e,
	0x3b, 0x69, 0x35, 0x43, 0x4a, 0x3f, 0x58, 0xcd, 0x0e, 0xdc, 0x8d, 0x90, 0x16, 0x63, 0xfc, 0x60,
	0x4d, 0x4f, 0x4c, 0x04, 0xe6, 0x55, 0x13, 0xfc, 0xd6, 0x80, 0xd5, 0x2d, 0x81, 0x44, 0x61, 0x84,
	0xe7, 0x05, 0x4a, 0x55, 0x65, 0x4f, 0x58, 0xa0, 0x92, 0xe9, 0x3a, 0x24, 0xa4, 0xa6, 0xd4, 0x58,
	0x16, 0x33, 0x9a, 0xbb, 0xfc, 0x75, 0x52, 0x96, 0x85, 0x34, 0x2f, 0x09, 0xba, 0x06, 0x9b, 0xae,
	0x06, 0x59, 0x36, 0x74, 0xc5, 0xa9, 0x25, 0x48, 0x62, 0x8a, 0xdc, 0x12, 0x74, 0xd5, 0x7e, 0x09,
	0x4b, 0xa5, 0x25, 0xc5, 0x52, 0xe4, 0x85, 0x32, 0xd5, 0xde, 0x8c, 0x7a, 0x0e, 0x3e, 0xb4, 0xa8,
	0xff, 0x02, 0x56, 0x28, 0x51, 0x24, 0x2e, 0xb9, 0x13, 0x26, 0xd5, 0xa0, 0xb3, 0xd6, 0x5c, 0x5f,
	0x78, 0xda, 0xdf, 0x18, 0x11, 0x45, 0xdc, 0x0d, 0x42, 0x77, 0xe9, 0x68, 0x89, 0x56, 0xe0, 0x8f,
	0x4c, 0x2a, 0xff, 0x1b, 0xe8, 0x97, 0xc2, 0x29, 0x4a, 0x49, 0x4e, 0x31, 0x3e, 0x23, 0xf2, 0xcc,
	0x74, 0x4b, 0x37, 0xf2, 0x1d, 0x6d, 0xd7, 0x92, 0x76, 0x88, 0x3c, 0xd3, 0x95, 0x93, 0x72, 0x8a,
	0x83, 0x45, 0xe3, 0x91, 0xf9, 0x0e, 0xfe, 0xf1, 0x60, 0xf5, 0x0a, 0x73, 0x3a, 0x64, 0x12, 0xc5,
	0x05, 0x1b, 0xd7, 0xc2, 0xdc, 0x75, 0x48, 0x48, 0xfd, 0x87, 0x00, 0x44, 0xc6, 0x8c, 0x5a, 0xbf,
	0x1b, 0x6b, 0x4d, 0xdd, 0xe8, 0x44, 0x86, 0xd4, 0xb8, 0x76, 0x17, 0x3a, 0x26, 0x6e, 0xd2, 0x84,
	0xad, 0x19, 0xb5, 0x75, 0xd8, 0xa4, 0xbf, 0x01, 0xab, 0xa5, 0xc7, 0xd6, 0x8a, 0x75, 0xd8, 0x8e,
	0x89, 0x15, 0x51, 0x4f, 0x99, 0xf1, 0xf7, 0x09, 0xac, 0x92, 0x4c, 0xbe, 0x46, 0x81, 0x34, 0xae,
	0x59, 0x6b, 0x1b, 0x6b, 0xcb, 0x25, 0x69, 0x58, 0x5a, 0xfd, 0x16, 0xee, 0x09, 0x1c, 0x23, 0xbb,
	0x40, 0x1a, 0x9b, 0xd8, 0x9e, 0x08, 0x9e, 0x56, 0x81, 0xed, 0x46, 0xfd, 0x92, 0xac, 0x2f, 0xfc,
	0x52, 0xf0, 0x54, 0x8b, 0x05, 0x12, 0xfc, 0xad, 0x84, 0xcb, 0xf7, 0x2b, 0x99, 0xe7, 0xfa, 0x2a,
	0x32, 0xe7, 0x99, 0xc4, 0xf8, 0x42, 0xcf, 0x8a, 0x2a, 0x10, 0x0b, 0x4f, 0x7b, 0x1b, 0x91, 0xa3,
	0x99, 0x31, 0xa2, 0xaf, 0x56, 0x3b, 0x1a, 0xa3, 0x05, 0xf4, 0x75, 0x25, 0xfc, 0x54, 0xa8, 0x1b,
	0x35, 0xfb, 0x97, 0x07, 0x8b, 0x53, 0x4c, 0x3a, 0x55, 0x8c, 0xe6, 0x95, 0xb1, 0x36, 0xa3, 0x79,
	0x48, 0xfd, 0xc7, 0xb0, 0x6c, 0xf5, 0xe7, 0x82, 0xf3, 0x93, 0xf8, 0x98, 0xf3, 0xc4, 0xf4, 0xc6,
	0xed, 0x9d, 0x8f, 0xa2, 0x9e, 0xa1, 0xec, 0x6b, 0xc2, 0x26, 0xe7, 0x89, 0xff, 0x05, 0x58, 0x44,
	0xb7, 0x83, 0xe5, 0x6c, 0x1a, 0x4e, 0x2f, 0xba, 0x63, 0xf0, 0x90, 0x24, 0x86, 0xef, 0x29, 0xf4,
	0x2d, 0x9f, 0x64, 0xa7, 0x19, 0x51, 0x85, 0x40, 0xcb, 0xdd, 0x32, 0xdc, 0x8d, 0xc8, 0x37, 0xd4,
	0x83, 0x92, 0xa8, 0x65, 0x36, 0x17, 0x61, 0xa1, 0xe6, 0xc7, 0xe6, 0x02, 0x74, 0x27, 0xa6, 0x36,
	0x57, 0x60, 0x69, 0x46, 0x5f, 0xf0, 0x2b, 0xdc, 0x3d, 0x40, 0x65, 0xeb, 0xd9, 0xa6, 0x7a, 0xbe,
	0xb8, 0x4e, 0x57, 0x7b, 0x63, 0xb6, 0xda, 0x57, 0xa1, 0x6d, 0xea, 0xcf, 0x6d, 0xbd, 0x96, 0x2e,
	0xf4, 0x20, 0x81, 0x9e, 0xf6, 0x55, 0x1b, 0x9b, 0xaf, 0x67, 0xa6, 0x7d, 0x68, 0xcc, 0xfa, 0xf0,
	0x10, 0xba, 0x93, 0x8b, 0x38, 0x43, 0x15, 0x10, 0x48, 0x58, 0x2b, 0x57, 0xfa, 0x81, 0xd5, 0x38,
	0x42, 0xa9, 0x58, 0x46, 0x14, 0xe3, 0x73, 0xf6, 0x6c, 0x6d, 0x68, 0x35, 0xa6, 0x86, 0xd6, 0xbb,
	0xc6, 0x5c, 0x70, 0x0e, 0x9f, 0xda, 0x55, 0x7b, 0x73, 0x26, 0x5f, 0xc0, 0xa3, 0x11, 0x93, 0xe4,
	0x38, 0xf9, 0xaf, 0x36, 0x83, 0x67, 0x30, 0xd8, 0x46, 0x75, 0x24, 0x91, 0x9a, 0x9d, 0x11, 0x61,
	0xce, 0x85, 0xba, 0x6e, 0x73, 0xfc, 0xee, 0x41, 0xdf, 0x6e, 0x8e, 0x90, 0x62, 0xa6, 0x98, 0xba,
	0x74, 0x12, 0x8f, 0x60, 0x81, 0x8c, 0xc7, 0x28, 0x25, 0x17, 0x95, 0x14, 0x94, 0x50, 0x48, 0xfd,
	0xcf, 0x60, 0x71, 0xc2, 0xa0, 0x2e, 0x73, 0x74, 0x89, 0xbd, 0x53, 0x82, 0x87, 0x97, 0x39, 0xea,
	0xc9, 0x37, 0x61, 0x7a, 0xeb, 0x11, 0xb5, 0x52, 0x92, 0xf6, 0xeb, 0x0f, 0x96, 0x09, 0xff, 0xa9,
	0xe0, 0x85, 0x69, 0x50, 0x3b, 0x27, 0x97, 0x4a, 0xc2, 0xb6, 0xc6, 0x43, 0x1a, 0xfc, 0xe1, 0x41,
	0x7f, 0xe8, 0xb0, 0x5d, 0x54, 0x67, 0x9c, 0xfe, 0x5f, 0x5c, 0x9f, 0xe9, 0x88, 0xf6, 0x4c, 0x47,
	0x04, 0x5b, 0xb0, 0xbe, 0x95, 0x20, 0x11, 0x65, 0xe1, 0xef, 0xca, 0xf3, 0x5a, 0x35, 0xb8, 0x4d,
	0x5a, 0x65, 0x56, 0x2f, 0x93, 0x5a, 0x66, 0xf5, 0x31, 0xa4, 0xc1, 0x31, 0xdc, 0x1f, 0xe1, 0x38,
	0x21, 0xa2, 0xca, 0xac, 0x1e, 0x25, 0x4e, 0xec, 0x73, 0xe8, 0x31, 0x07, 0xdb, 0x11, 0xe3, 0xa4,
	0x17, 0x59, 0x9d, 0xf9, 0x9a, 0xd6, 0x0d, 0x86, 0xd0, 0xb7, 0x7d, 0x32, 0x53, 0x3c, 0xef, 0x72,
	0xca, 0x5f, 0x86, 0x66, 0xd5, 0x13, 0xfa, 0x33, 0xf8, 0xdb, 0x83, 0x7b, 0x65, 0x01, 0xe6, 0xe5,
	0x88, 0x9e, 0x6f, 0x78, 0xbd, 0xa5, 0x4c, 0x23, 0x55, 0x67, 0xe9, 0x4f, 0xfd, 0xc0, 0x92, 0x8a,
	0xa8, 0x42, 0xba, 0x54, 0xb8, 0xd3, 0xf4, 0xd0, 0x69, 0xcf, 0x0c, 0x9d, 0x2b, 0xa2, 0xd3, 0xb9,
	0x2a, 0x3a, 0x5f, 0x81, 0x9f, 0x0b, 0x76, 0x41, 0x14, 0xba, 0x75, 0x51, 0x7b, 0x87, 0x2c, 0x3b,
	0x8a, 0xe1, 0xd4, 0x5b, 0x3d, 0xd8, 0x86, 0xd6, 0x91, 0x44, 0xf1, 0x1e, 0xc1, 0xd1, 0xcf, 0xe3,
	0x13, 0x26, 0xa4, 0xb2, 0x8b, 0x25, 0xb2, 0x87, 0xe0, 0x3b, 0x78, 0x78, 0x75, 0x65, 0xb8, 0xb0,
	0x3d, 0x80, 0x76, 0x21, 0x51, 0xc8, 0x81, 0x67, 0xd6, 0x63, 0x7b, 0x43, 0x9b, 0x8d, 0x2c, 0x76,
	0xdc, 0x31, 0x7f, 0xd0, 0x9e, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xb2, 0x60, 0xa0, 0xbe,
	0x0d, 0x00, 0x00,
}
