// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/params/params.proto

package params

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitNDIDParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitNDIDParams) Reset()         { *m = InitNDIDParams{} }
func (m *InitNDIDParams) String() string { return proto.CompactTextString(m) }
func (*InitNDIDParams) ProtoMessage()    {}
func (*InitNDIDParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{0}
}
func (m *InitNDIDParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitNDIDParams.Unmarshal(m, b)
}
func (m *InitNDIDParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitNDIDParams.Marshal(b, m, deterministic)
}
func (dst *InitNDIDParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitNDIDParams.Merge(dst, src)
}
func (m *InitNDIDParams) XXX_Size() int {
	return xxx_messageInfo_InitNDIDParams.Size(m)
}
func (m *InitNDIDParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InitNDIDParams.DiscardUnknown(m)
}

var xxx_messageInfo_InitNDIDParams proto.InternalMessageInfo

func (m *InitNDIDParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *InitNDIDParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *InitNDIDParams) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type RegisterNodeParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,3,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,6,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,7,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeParams) Reset()         { *m = RegisterNodeParams{} }
func (m *RegisterNodeParams) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeParams) ProtoMessage()    {}
func (*RegisterNodeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{1}
}
func (m *RegisterNodeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeParams.Unmarshal(m, b)
}
func (m *RegisterNodeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeParams.Marshal(b, m, deterministic)
}
func (dst *RegisterNodeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeParams.Merge(dst, src)
}
func (m *RegisterNodeParams) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeParams.Size(m)
}
func (m *RegisterNodeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeParams proto.InternalMessageInfo

func (m *RegisterNodeParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RegisterNodeParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RegisterNodeParams) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *RegisterNodeParams) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *RegisterNodeParams) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RegisterNodeParams) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *RegisterNodeParams) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

type UpdateNodeParams struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeParams) Reset()         { *m = UpdateNodeParams{} }
func (m *UpdateNodeParams) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeParams) ProtoMessage()    {}
func (*UpdateNodeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{2}
}
func (m *UpdateNodeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeParams.Unmarshal(m, b)
}
func (m *UpdateNodeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeParams.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeParams.Merge(dst, src)
}
func (m *UpdateNodeParams) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeParams.Size(m)
}
func (m *UpdateNodeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeParams proto.InternalMessageInfo

func (m *UpdateNodeParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *UpdateNodeParams) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

type SetValidatorParams struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Power                int64    `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValidatorParams) Reset()         { *m = SetValidatorParams{} }
func (m *SetValidatorParams) String() string { return proto.CompactTextString(m) }
func (*SetValidatorParams) ProtoMessage()    {}
func (*SetValidatorParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{3}
}
func (m *SetValidatorParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValidatorParams.Unmarshal(m, b)
}
func (m *SetValidatorParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValidatorParams.Marshal(b, m, deterministic)
}
func (dst *SetValidatorParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValidatorParams.Merge(dst, src)
}
func (m *SetValidatorParams) XXX_Size() int {
	return xxx_messageInfo_SetValidatorParams.Size(m)
}
func (m *SetValidatorParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValidatorParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetValidatorParams proto.InternalMessageInfo

func (m *SetValidatorParams) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SetValidatorParams) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type SetPriceFuncParams struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPriceFuncParams) Reset()         { *m = SetPriceFuncParams{} }
func (m *SetPriceFuncParams) String() string { return proto.CompactTextString(m) }
func (*SetPriceFuncParams) ProtoMessage()    {}
func (*SetPriceFuncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{4}
}
func (m *SetPriceFuncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPriceFuncParams.Unmarshal(m, b)
}
func (m *SetPriceFuncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPriceFuncParams.Marshal(b, m, deterministic)
}
func (dst *SetPriceFuncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPriceFuncParams.Merge(dst, src)
}
func (m *SetPriceFuncParams) XXX_Size() int {
	return xxx_messageInfo_SetPriceFuncParams.Size(m)
}
func (m *SetPriceFuncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPriceFuncParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetPriceFuncParams proto.InternalMessageInfo

func (m *SetPriceFuncParams) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *SetPriceFuncParams) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetPriceFuncParams struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceFuncParams) Reset()         { *m = GetPriceFuncParams{} }
func (m *GetPriceFuncParams) String() string { return proto.CompactTextString(m) }
func (*GetPriceFuncParams) ProtoMessage()    {}
func (*GetPriceFuncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{5}
}
func (m *GetPriceFuncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceFuncParams.Unmarshal(m, b)
}
func (m *GetPriceFuncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceFuncParams.Marshal(b, m, deterministic)
}
func (dst *GetPriceFuncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceFuncParams.Merge(dst, src)
}
func (m *GetPriceFuncParams) XXX_Size() int {
	return xxx_messageInfo_GetPriceFuncParams.Size(m)
}
func (m *GetPriceFuncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceFuncParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceFuncParams proto.InternalMessageInfo

func (m *GetPriceFuncParams) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type SetNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNodeTokenParams) Reset()         { *m = SetNodeTokenParams{} }
func (m *SetNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*SetNodeTokenParams) ProtoMessage()    {}
func (*SetNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{6}
}
func (m *SetNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNodeTokenParams.Unmarshal(m, b)
}
func (m *SetNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *SetNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNodeTokenParams.Merge(dst, src)
}
func (m *SetNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_SetNodeTokenParams.Size(m)
}
func (m *SetNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetNodeTokenParams proto.InternalMessageInfo

func (m *SetNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SetNodeTokenParams) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type AddNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeTokenParams) Reset()         { *m = AddNodeTokenParams{} }
func (m *AddNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*AddNodeTokenParams) ProtoMessage()    {}
func (*AddNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{7}
}
func (m *AddNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeTokenParams.Unmarshal(m, b)
}
func (m *AddNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *AddNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeTokenParams.Merge(dst, src)
}
func (m *AddNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_AddNodeTokenParams.Size(m)
}
func (m *AddNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeTokenParams proto.InternalMessageInfo

func (m *AddNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddNodeTokenParams) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReduceNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceNodeTokenParams) Reset()         { *m = ReduceNodeTokenParams{} }
func (m *ReduceNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*ReduceNodeTokenParams) ProtoMessage()    {}
func (*ReduceNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{8}
}
func (m *ReduceNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceNodeTokenParams.Unmarshal(m, b)
}
func (m *ReduceNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *ReduceNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceNodeTokenParams.Merge(dst, src)
}
func (m *ReduceNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_ReduceNodeTokenParams.Size(m)
}
func (m *ReduceNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceNodeTokenParams proto.InternalMessageInfo

func (m *ReduceNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ReduceNodeTokenParams) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GetNodeTokenParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeTokenParams) Reset()         { *m = GetNodeTokenParams{} }
func (m *GetNodeTokenParams) String() string { return proto.CompactTextString(m) }
func (*GetNodeTokenParams) ProtoMessage()    {}
func (*GetNodeTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{9}
}
func (m *GetNodeTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeTokenParams.Unmarshal(m, b)
}
func (m *GetNodeTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeTokenParams.Marshal(b, m, deterministic)
}
func (dst *GetNodeTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeTokenParams.Merge(dst, src)
}
func (m *GetNodeTokenParams) XXX_Size() int {
	return xxx_messageInfo_GetNodeTokenParams.Size(m)
}
func (m *GetNodeTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeTokenParams proto.InternalMessageInfo

func (m *GetNodeTokenParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type CreateRequestParams struct {
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64                  `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64                `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64                `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64                  `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	DataRequestList      []*DataRequestInParams `protobuf:"bytes,6,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string                 `protobuf:"bytes,7,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	ResponseList         []*ResponseInParams    `protobuf:"bytes,8,rep,name=response_list,json=responseList,proto3" json:"response_list,omitempty"`
	Closed               bool                   `protobuf:"varint,9,opt,name=closed,proto3" json:"closed,omitempty"`
	TimedOut             bool                   `protobuf:"varint,10,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	CanAddAccessor       bool                   `protobuf:"varint,11,opt,name=can_add_accessor,json=canAddAccessor,proto3" json:"can_add_accessor,omitempty"`
	Owner                string                 `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"`
	Mode                 int64                  `protobuf:"varint,13,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateRequestParams) Reset()         { *m = CreateRequestParams{} }
func (m *CreateRequestParams) String() string { return proto.CompactTextString(m) }
func (*CreateRequestParams) ProtoMessage()    {}
func (*CreateRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{10}
}
func (m *CreateRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestParams.Unmarshal(m, b)
}
func (m *CreateRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestParams.Marshal(b, m, deterministic)
}
func (dst *CreateRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestParams.Merge(dst, src)
}
func (m *CreateRequestParams) XXX_Size() int {
	return xxx_messageInfo_CreateRequestParams.Size(m)
}
func (m *CreateRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestParams proto.InternalMessageInfo

func (m *CreateRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateRequestParams) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *CreateRequestParams) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *CreateRequestParams) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *CreateRequestParams) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *CreateRequestParams) GetDataRequestList() []*DataRequestInParams {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *CreateRequestParams) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *CreateRequestParams) GetResponseList() []*ResponseInParams {
	if m != nil {
		return m.ResponseList
	}
	return nil
}

func (m *CreateRequestParams) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *CreateRequestParams) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *CreateRequestParams) GetCanAddAccessor() bool {
	if m != nil {
		return m.CanAddAccessor
	}
	return false
}

func (m *CreateRequestParams) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateRequestParams) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type DataRequestInParams struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	Request_ParamsHash   string   `protobuf:"bytes,4,opt,name=request_Params_hash,json=requestParamsHash,proto3" json:"request_Params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequestInParams) Reset()         { *m = DataRequestInParams{} }
func (m *DataRequestInParams) String() string { return proto.CompactTextString(m) }
func (*DataRequestInParams) ProtoMessage()    {}
func (*DataRequestInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{11}
}
func (m *DataRequestInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequestInParams.Unmarshal(m, b)
}
func (m *DataRequestInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequestInParams.Marshal(b, m, deterministic)
}
func (dst *DataRequestInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequestInParams.Merge(dst, src)
}
func (m *DataRequestInParams) XXX_Size() int {
	return xxx_messageInfo_DataRequestInParams.Size(m)
}
func (m *DataRequestInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequestInParams.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequestInParams proto.InternalMessageInfo

func (m *DataRequestInParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequestInParams) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequestInParams) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequestInParams) GetRequest_ParamsHash() string {
	if m != nil {
		return m.Request_ParamsHash
	}
	return ""
}

func (m *DataRequestInParams) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequestInParams) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type ResponseInParams struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,2,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityProof        string   `protobuf:"bytes,5,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	PrivateProofHash     string   `protobuf:"bytes,6,opt,name=private_proof_hash,json=privateProofHash,proto3" json:"private_proof_hash,omitempty"`
	IdpId                string   `protobuf:"bytes,7,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	ValidProof           string   `protobuf:"bytes,8,opt,name=valid_proof,json=validProof,proto3" json:"valid_proof,omitempty"`
	ValidIal             string   `protobuf:"bytes,9,opt,name=valid_ial,json=validIal,proto3" json:"valid_ial,omitempty"`
	ValidSignature       string   `protobuf:"bytes,10,opt,name=valid_signature,json=validSignature,proto3" json:"valid_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInParams) Reset()         { *m = ResponseInParams{} }
func (m *ResponseInParams) String() string { return proto.CompactTextString(m) }
func (*ResponseInParams) ProtoMessage()    {}
func (*ResponseInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{12}
}
func (m *ResponseInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInParams.Unmarshal(m, b)
}
func (m *ResponseInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInParams.Marshal(b, m, deterministic)
}
func (dst *ResponseInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInParams.Merge(dst, src)
}
func (m *ResponseInParams) XXX_Size() int {
	return xxx_messageInfo_ResponseInParams.Size(m)
}
func (m *ResponseInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInParams.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInParams proto.InternalMessageInfo

func (m *ResponseInParams) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *ResponseInParams) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *ResponseInParams) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResponseInParams) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ResponseInParams) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *ResponseInParams) GetPrivateProofHash() string {
	if m != nil {
		return m.PrivateProofHash
	}
	return ""
}

func (m *ResponseInParams) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

func (m *ResponseInParams) GetValidProof() string {
	if m != nil {
		return m.ValidProof
	}
	return ""
}

func (m *ResponseInParams) GetValidIal() string {
	if m != nil {
		return m.ValidIal
	}
	return ""
}

func (m *ResponseInParams) GetValidSignature() string {
	if m != nil {
		return m.ValidSignature
	}
	return ""
}

type CloseRequestParams struct {
	RequestId            string           `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseValidList    []*ResponseValid `protobuf:"bytes,2,rep,name=response_valid_list,json=responseValidList,proto3" json:"response_valid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CloseRequestParams) Reset()         { *m = CloseRequestParams{} }
func (m *CloseRequestParams) String() string { return proto.CompactTextString(m) }
func (*CloseRequestParams) ProtoMessage()    {}
func (*CloseRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{13}
}
func (m *CloseRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequestParams.Unmarshal(m, b)
}
func (m *CloseRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequestParams.Marshal(b, m, deterministic)
}
func (dst *CloseRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequestParams.Merge(dst, src)
}
func (m *CloseRequestParams) XXX_Size() int {
	return xxx_messageInfo_CloseRequestParams.Size(m)
}
func (m *CloseRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequestParams proto.InternalMessageInfo

func (m *CloseRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CloseRequestParams) GetResponseValidList() []*ResponseValid {
	if m != nil {
		return m.ResponseValidList
	}
	return nil
}

type TimeOutRequestParams struct {
	RequestId            string           `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseValidList    []*ResponseValid `protobuf:"bytes,2,rep,name=response_valid_list,json=responseValidList,proto3" json:"response_valid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TimeOutRequestParams) Reset()         { *m = TimeOutRequestParams{} }
func (m *TimeOutRequestParams) String() string { return proto.CompactTextString(m) }
func (*TimeOutRequestParams) ProtoMessage()    {}
func (*TimeOutRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{14}
}
func (m *TimeOutRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOutRequestParams.Unmarshal(m, b)
}
func (m *TimeOutRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOutRequestParams.Marshal(b, m, deterministic)
}
func (dst *TimeOutRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOutRequestParams.Merge(dst, src)
}
func (m *TimeOutRequestParams) XXX_Size() int {
	return xxx_messageInfo_TimeOutRequestParams.Size(m)
}
func (m *TimeOutRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOutRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOutRequestParams proto.InternalMessageInfo

func (m *TimeOutRequestParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *TimeOutRequestParams) GetResponseValidList() []*ResponseValid {
	if m != nil {
		return m.ResponseValidList
	}
	return nil
}

type ResponseValid struct {
	IdpId string `protobuf:"bytes,1,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	// Types that are valid to be assigned to ValidProof:
	//	*ResponseValid_ValidProofBool
	ValidProof isResponseValid_ValidProof `protobuf_oneof:"valid_proof"`
	// Types that are valid to be assigned to ValidIal:
	//	*ResponseValid_ValidIalBool
	ValidIal isResponseValid_ValidIal `protobuf_oneof:"valid_ial"`
	// Types that are valid to be assigned to ValidSignature:
	//	*ResponseValid_ValidSignatureBool
	ValidSignature       isResponseValid_ValidSignature `protobuf_oneof:"valid_signature"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ResponseValid) Reset()         { *m = ResponseValid{} }
func (m *ResponseValid) String() string { return proto.CompactTextString(m) }
func (*ResponseValid) ProtoMessage()    {}
func (*ResponseValid) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{15}
}
func (m *ResponseValid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseValid.Unmarshal(m, b)
}
func (m *ResponseValid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseValid.Marshal(b, m, deterministic)
}
func (dst *ResponseValid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseValid.Merge(dst, src)
}
func (m *ResponseValid) XXX_Size() int {
	return xxx_messageInfo_ResponseValid.Size(m)
}
func (m *ResponseValid) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseValid.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseValid proto.InternalMessageInfo

func (m *ResponseValid) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

type isResponseValid_ValidProof interface {
	isResponseValid_ValidProof()
}

type ResponseValid_ValidProofBool struct {
	ValidProofBool bool `protobuf:"varint,2,opt,name=valid_proof_bool,json=validProofBool,proto3,oneof"`
}

func (*ResponseValid_ValidProofBool) isResponseValid_ValidProof() {}

func (m *ResponseValid) GetValidProof() isResponseValid_ValidProof {
	if m != nil {
		return m.ValidProof
	}
	return nil
}

func (m *ResponseValid) GetValidProofBool() bool {
	if x, ok := m.GetValidProof().(*ResponseValid_ValidProofBool); ok {
		return x.ValidProofBool
	}
	return false
}

type isResponseValid_ValidIal interface {
	isResponseValid_ValidIal()
}

type ResponseValid_ValidIalBool struct {
	ValidIalBool bool `protobuf:"varint,3,opt,name=valid_ial_bool,json=validIalBool,proto3,oneof"`
}

func (*ResponseValid_ValidIalBool) isResponseValid_ValidIal() {}

func (m *ResponseValid) GetValidIal() isResponseValid_ValidIal {
	if m != nil {
		return m.ValidIal
	}
	return nil
}

func (m *ResponseValid) GetValidIalBool() bool {
	if x, ok := m.GetValidIal().(*ResponseValid_ValidIalBool); ok {
		return x.ValidIalBool
	}
	return false
}

type isResponseValid_ValidSignature interface {
	isResponseValid_ValidSignature()
}

type ResponseValid_ValidSignatureBool struct {
	ValidSignatureBool bool `protobuf:"varint,4,opt,name=valid_signature_bool,json=validSignatureBool,proto3,oneof"`
}

func (*ResponseValid_ValidSignatureBool) isResponseValid_ValidSignature() {}

func (m *ResponseValid) GetValidSignature() isResponseValid_ValidSignature {
	if m != nil {
		return m.ValidSignature
	}
	return nil
}

func (m *ResponseValid) GetValidSignatureBool() bool {
	if x, ok := m.GetValidSignature().(*ResponseValid_ValidSignatureBool); ok {
		return x.ValidSignatureBool
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResponseValid) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResponseValid_OneofMarshaler, _ResponseValid_OneofUnmarshaler, _ResponseValid_OneofSizer, []interface{}{
		(*ResponseValid_ValidProofBool)(nil),
		(*ResponseValid_ValidIalBool)(nil),
		(*ResponseValid_ValidSignatureBool)(nil),
	}
}

func _ResponseValid_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResponseValid)
	// valid_proof
	switch x := m.ValidProof.(type) {
	case *ResponseValid_ValidProofBool:
		t := uint64(0)
		if x.ValidProofBool {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ResponseValid.ValidProof has unexpected type %T", x)
	}
	// valid_ial
	switch x := m.ValidIal.(type) {
	case *ResponseValid_ValidIalBool:
		t := uint64(0)
		if x.ValidIalBool {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ResponseValid.ValidIal has unexpected type %T", x)
	}
	// valid_signature
	switch x := m.ValidSignature.(type) {
	case *ResponseValid_ValidSignatureBool:
		t := uint64(0)
		if x.ValidSignatureBool {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ResponseValid.ValidSignature has unexpected type %T", x)
	}
	return nil
}

func _ResponseValid_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResponseValid)
	switch tag {
	case 2: // valid_proof.valid_proof_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ValidProof = &ResponseValid_ValidProofBool{x != 0}
		return true, err
	case 3: // valid_ial.valid_ial_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ValidIal = &ResponseValid_ValidIalBool{x != 0}
		return true, err
	case 4: // valid_signature.valid_signature_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ValidSignature = &ResponseValid_ValidSignatureBool{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _ResponseValid_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResponseValid)
	// valid_proof
	switch x := m.ValidProof.(type) {
	case *ResponseValid_ValidProofBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// valid_ial
	switch x := m.ValidIal.(type) {
	case *ResponseValid_ValidIalBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// valid_signature
	switch x := m.ValidSignature.(type) {
	case *ResponseValid_ValidSignatureBool:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetDataReceivedParams struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsId                 string   `protobuf:"bytes,3,opt,name=as_id,json=asId,proto3" json:"as_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataReceivedParams) Reset()         { *m = SetDataReceivedParams{} }
func (m *SetDataReceivedParams) String() string { return proto.CompactTextString(m) }
func (*SetDataReceivedParams) ProtoMessage()    {}
func (*SetDataReceivedParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_cd00800fedffde18, []int{16}
}
func (m *SetDataReceivedParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataReceivedParams.Unmarshal(m, b)
}
func (m *SetDataReceivedParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataReceivedParams.Marshal(b, m, deterministic)
}
func (dst *SetDataReceivedParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataReceivedParams.Merge(dst, src)
}
func (m *SetDataReceivedParams) XXX_Size() int {
	return xxx_messageInfo_SetDataReceivedParams.Size(m)
}
func (m *SetDataReceivedParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataReceivedParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataReceivedParams proto.InternalMessageInfo

func (m *SetDataReceivedParams) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SetDataReceivedParams) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *SetDataReceivedParams) GetAsId() string {
	if m != nil {
		return m.AsId
	}
	return ""
}

func init() {
	proto.RegisterType((*InitNDIDParams)(nil), "InitNDIDParams")
	proto.RegisterType((*RegisterNodeParams)(nil), "RegisterNodeParams")
	proto.RegisterType((*UpdateNodeParams)(nil), "UpdateNodeParams")
	proto.RegisterType((*SetValidatorParams)(nil), "SetValidatorParams")
	proto.RegisterType((*SetPriceFuncParams)(nil), "SetPriceFuncParams")
	proto.RegisterType((*GetPriceFuncParams)(nil), "GetPriceFuncParams")
	proto.RegisterType((*SetNodeTokenParams)(nil), "SetNodeTokenParams")
	proto.RegisterType((*AddNodeTokenParams)(nil), "AddNodeTokenParams")
	proto.RegisterType((*ReduceNodeTokenParams)(nil), "ReduceNodeTokenParams")
	proto.RegisterType((*GetNodeTokenParams)(nil), "GetNodeTokenParams")
	proto.RegisterType((*CreateRequestParams)(nil), "CreateRequestParams")
	proto.RegisterType((*DataRequestInParams)(nil), "DataRequestInParams")
	proto.RegisterType((*ResponseInParams)(nil), "ResponseInParams")
	proto.RegisterType((*CloseRequestParams)(nil), "CloseRequestParams")
	proto.RegisterType((*TimeOutRequestParams)(nil), "TimeOutRequestParams")
	proto.RegisterType((*ResponseValid)(nil), "ResponseValid")
	proto.RegisterType((*SetDataReceivedParams)(nil), "SetDataReceivedParams")
}

func init() { proto.RegisterFile("protos/params/params.proto", fileDescriptor_params_cd00800fedffde18) }

var fileDescriptor_params_cd00800fedffde18 = []byte{
	// 991 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x61, 0x6f, 0x1c, 0x35,
	0x10, 0x65, 0xef, 0x72, 0xdb, 0xdb, 0x49, 0x72, 0xb9, 0x38, 0x97, 0x76, 0x45, 0x8b, 0x88, 0x56,
	0x02, 0x4e, 0x15, 0x0d, 0x28, 0x08, 0x3e, 0x56, 0x5c, 0x1a, 0x4a, 0x56, 0x40, 0x1a, 0x6d, 0x0a,
	0xdf, 0xd0, 0xca, 0x59, 0x3b, 0x89, 0xe9, 0xee, 0x7a, 0xb1, 0xbd, 0x49, 0xf3, 0xeb, 0xf8, 0x21,
	0xa8, 0xbf, 0x05, 0xe4, 0xb1, 0x37, 0x77, 0x09, 0x95, 0xb8, 0xaa, 0x52, 0x3f, 0xc5, 0x7e, 0xf3,
	0xec, 0xb9, 0x99, 0xf7, 0x3c, 0x1b, 0xf8, 0xb8, 0x51, 0xd2, 0x48, 0xfd, 0x55, 0x43, 0x15, 0xad,
	0xba, 0x3f, 0xbb, 0x08, 0x26, 0x06, 0x46, 0x69, 0x2d, 0xcc, 0xd1, 0x41, 0x7a, 0x70, 0x8c, 0x38,
	0x79, 0x00, 0xf7, 0x6a, 0xc9, 0x78, 0x2e, 0x58, 0x1c, 0xec, 0x04, 0xd3, 0x28, 0x0b, 0xed, 0x36,
	0x65, 0xe4, 0x13, 0x80, 0xa6, 0x3d, 0x2d, 0x45, 0x91, 0xbf, 0xe2, 0xd7, 0x71, 0x0f, 0x63, 0x91,
	0x43, 0x7e, 0xe2, 0xd7, 0xe4, 0x31, 0x6c, 0x56, 0x54, 0x1b, 0xae, 0xf2, 0x05, 0x56, 0x1f, 0x59,
	0x1b, 0x2e, 0x70, 0xdc, 0x71, 0x93, 0xbf, 0x03, 0x20, 0x19, 0x3f, 0x17, 0x16, 0x3d, 0x92, 0x8c,
	0x7f, 0xb8, 0xd4, 0xe4, 0x21, 0x44, 0x98, 0xa3, 0xa6, 0x15, 0x8f, 0x57, 0x90, 0x33, 0xb4, 0xc0,
	0x11, 0xad, 0x38, 0x21, 0xb0, 0xa2, 0x64, 0xc9, 0xe3, 0x01, 0xe2, 0xb8, 0xb6, 0x3f, 0xaa, 0xa2,
	0xaf, 0x73, 0x41, 0xcb, 0x38, 0xdc, 0x09, 0xa6, 0x41, 0x16, 0x56, 0xf4, 0x75, 0x4a, 0xcb, 0x2e,
	0x40, 0x69, 0x19, 0xdf, 0xbb, 0x09, 0xcc, 0x68, 0x99, 0xfc, 0x0e, 0xe3, 0x5f, 0x1b, 0x46, 0x0d,
	0x5f, 0x28, 0xed, 0x76, 0x05, 0xc1, 0x52, 0x15, 0xf4, 0xde, 0xde, 0xbc, 0x14, 0xc8, 0x09, 0x37,
	0xbf, 0xd1, 0x52, 0x30, 0x6a, 0xa4, 0x5a, 0x2e, 0xc1, 0x04, 0x06, 0x8d, 0xbc, 0xe2, 0x0a, 0x2f,
	0xed, 0x67, 0x6e, 0x93, 0x3c, 0xc5, 0xab, 0x8e, 0x95, 0x28, 0xf8, 0xf3, 0xb6, 0x2e, 0xfc, 0x55,
	0x04, 0x56, 0xce, 0xda, 0xba, 0xf0, 0x97, 0xe0, 0x1a, 0xcf, 0x5b, 0x1a, 0x9e, 0x0f, 0x32, 0xb7,
	0x49, 0xa6, 0x40, 0x7e, 0x5c, 0xea, 0x7c, 0xf2, 0x03, 0x66, 0xb2, 0x0d, 0x79, 0x29, 0x5f, 0xf1,
	0xfa, 0xff, 0x04, 0xbf, 0x0f, 0x21, 0xad, 0x64, 0x5b, 0x1b, 0x9f, 0xcf, 0xef, 0xec, 0x35, 0x33,
	0xc6, 0xde, 0xfb, 0x9a, 0x43, 0xd8, 0xce, 0x38, 0x6b, 0x0b, 0xfe, 0xde, 0x37, 0x3d, 0xc1, 0x0e,
	0x2c, 0x7b, 0x4d, 0xf2, 0xa6, 0x0f, 0x5b, 0xcf, 0x14, 0xa7, 0x86, 0x67, 0xfc, 0xcf, 0x96, 0x6b,
	0x33, 0x57, 0x4f, 0x39, 0x60, 0x7e, 0x26, 0xf2, 0x48, 0xca, 0xd0, 0x6a, 0xa2, 0xce, 0x05, 0x6b,
	0xbc, 0x7e, 0x61, 0x25, 0xea, 0x94, 0x35, 0x5d, 0xc0, 0x7a, 0xb0, 0xef, 0x3d, 0x28, 0xea, 0x99,
	0x37, 0xa7, 0x3d, 0x41, 0x4b, 0x34, 0xb9, 0x0b, 0x58, 0xd7, 0x7e, 0x01, 0x1b, 0x5d, 0x26, 0x23,
	0x2a, 0x2e, 0x5b, 0x83, 0x6e, 0xef, 0x67, 0x23, 0x0f, 0xbf, 0x74, 0x28, 0xf9, 0x1e, 0x36, 0x19,
	0x35, 0x34, 0xef, 0xd8, 0xa5, 0xd0, 0x26, 0x0e, 0x77, 0xfa, 0xd3, 0xd5, 0xbd, 0xc9, 0xee, 0x01,
	0x35, 0xd4, 0x57, 0x90, 0xfa, 0xa2, 0xb3, 0x0d, 0x36, 0x07, 0x7f, 0x16, 0xda, 0x90, 0xaf, 0x61,
	0xd2, 0x1d, 0xae, 0xb8, 0xd6, 0xf4, 0x9c, 0xe7, 0x17, 0x54, 0x5f, 0xe0, 0x6b, 0x89, 0x32, 0xe2,
	0x63, 0xbf, 0xb8, 0xd0, 0x21, 0xd5, 0x17, 0xe4, 0x3b, 0x58, 0x57, 0x5c, 0x37, 0xb2, 0xd6, 0xdc,
	0xe5, 0x1b, 0x62, 0xbe, 0xcd, 0xdd, 0xcc, 0xa3, 0x37, 0xc9, 0xd6, 0x3a, 0x1e, 0x66, 0xba, 0x0f,
	0x61, 0x51, 0x4a, 0xcd, 0x59, 0x1c, 0xed, 0x04, 0xd3, 0x61, 0xe6, 0x77, 0xf6, 0xb1, 0xdb, 0x22,
	0x59, 0x6e, 0xcb, 0x04, 0x0c, 0x0d, 0x11, 0x78, 0xd1, 0x1a, 0x32, 0x85, 0x71, 0x41, 0xeb, 0x9c,
	0x32, 0x96, 0xd3, 0xa2, 0xe0, 0x5a, 0x4b, 0x15, 0xaf, 0x22, 0x67, 0x54, 0xd0, 0x7a, 0xc6, 0xd8,
	0xcc, 0xa3, 0xd6, 0xfc, 0xf2, 0xaa, 0xe6, 0x2a, 0x5e, 0xc3, 0x5f, 0xee, 0x36, 0xd6, 0xe6, 0x95,
	0x64, 0x3c, 0x5e, 0xc7, 0xf6, 0xe1, 0x3a, 0xf9, 0x27, 0x80, 0xad, 0xb7, 0xf4, 0xc6, 0xea, 0xab,
	0xb9, 0xba, 0x14, 0xc5, 0x82, 0x27, 0x22, 0x8f, 0xa4, 0x8c, 0x3c, 0x02, 0xa0, 0x3a, 0x17, 0xcc,
	0x15, 0xdd, 0xdb, 0xe9, 0xdb, 0xa9, 0x44, 0x75, 0xca, 0xb0, 0xba, 0x6d, 0x08, 0x51, 0x64, 0x8d,
	0x1a, 0xf7, 0xb3, 0x81, 0xd5, 0x58, 0x93, 0x5d, 0xd8, 0xea, 0xda, 0xeb, 0xb2, 0xb8, 0xee, 0xba,
	0x99, 0xb6, 0xa9, 0x16, 0xfd, 0x85, 0xcd, 0x7d, 0x02, 0x5b, 0xb4, 0xd6, 0x57, 0x5c, 0x71, 0x96,
	0x2f, 0x64, 0x1b, 0x60, 0xb6, 0x71, 0x17, 0x9a, 0x75, 0x59, 0xbf, 0x85, 0x07, 0x8a, 0x17, 0x5c,
	0x5c, 0x72, 0x96, 0xa3, 0x11, 0xce, 0x94, 0xac, 0xe6, 0x2e, 0x88, 0xb2, 0x49, 0x17, 0xb6, 0x05,
	0x3f, 0x57, 0xb2, 0xb2, 0xc7, 0x92, 0xbf, 0x7a, 0x30, 0xbe, 0xab, 0x16, 0x19, 0x43, 0xdf, 0x3a,
	0x31, 0x40, 0x27, 0xda, 0xa5, 0x45, 0xac, 0x69, 0xdd, 0x63, 0xb2, 0x4b, 0xab, 0xa1, 0x36, 0xd4,
	0xb4, 0xda, 0x4f, 0x6e, 0xbf, 0x23, 0x8f, 0x20, 0xd2, 0xe2, 0xbc, 0xa6, 0xa6, 0x55, 0xdd, 0xc0,
	0x9e, 0x03, 0xe4, 0x33, 0x18, 0x09, 0xc6, 0x6b, 0x23, 0xcc, 0x75, 0xde, 0x28, 0x29, 0xcf, 0xfc,
	0xec, 0x5e, 0xef, 0xd0, 0x63, 0x0b, 0x92, 0x2f, 0x81, 0x34, 0x4a, 0x5c, 0x52, 0xc3, 0x1d, 0xcb,
	0xb5, 0x2a, 0x44, 0xea, 0xd8, 0x47, 0x90, 0x89, 0x9d, 0xda, 0x86, 0x50, 0xb0, 0xc6, 0x2a, 0xe5,
	0xac, 0x3a, 0x10, 0xac, 0x49, 0x19, 0xf9, 0x14, 0x56, 0x2f, 0xed, 0xd4, 0xf5, 0x89, 0x86, 0x18,
	0x03, 0x84, 0x5c, 0x96, 0x87, 0x10, 0x39, 0x82, 0x2d, 0x36, 0x72, 0xdf, 0x16, 0x04, 0xfc, 0xc3,
	0x73, 0xc1, 0x79, 0x35, 0x80, 0x94, 0x11, 0xc2, 0x27, 0x1d, 0x9a, 0x68, 0x20, 0xcf, 0xac, 0x7d,
	0xdf, 0x69, 0x42, 0x3c, 0xb5, 0x66, 0xf0, 0x2f, 0xc7, 0xa5, 0xb9, 0xb1, 0xd2, 0xea, 0xde, 0xe8,
	0xe6, 0xfd, 0xe0, 0x57, 0xc3, 0x9a, 0x63, 0x61, 0x8b, 0xb2, 0xb5, 0x30, 0xb1, 0x0f, 0xff, 0x45,
	0x6b, 0x3e, 0x68, 0xda, 0x37, 0x01, 0xac, 0xdf, 0x22, 0x2d, 0xf4, 0x3e, 0x58, 0xec, 0xfd, 0x63,
	0x18, 0x2f, 0xf4, 0x3e, 0x3f, 0x95, 0xd2, 0x99, 0x67, 0x78, 0xf8, 0x91, 0x6f, 0x20, 0x4a, 0xb0,
	0x2f, 0x65, 0x49, 0x3e, 0x87, 0xd1, 0x8d, 0x0c, 0x8e, 0xd9, 0x47, 0x66, 0x90, 0xad, 0x75, 0x6a,
	0x20, 0x6f, 0x0f, 0x26, 0x77, 0x14, 0x71, 0xec, 0x15, 0x64, 0xf7, 0x32, 0x72, 0x5b, 0x18, 0x7b,
	0x66, 0x7f, 0xfd, 0x96, 0x07, 0xf6, 0x57, 0x17, 0x14, 0xdf, 0xdf, 0xfc, 0x8f, 0xc2, 0xc9, 0x1f,
	0xb0, 0x7d, 0xc2, 0x8d, 0x9b, 0x08, 0xee, 0xb1, 0x2c, 0xd7, 0xd7, 0xdb, 0xf3, 0xa2, 0x77, 0x77,
	0x5e, 0x6c, 0xc1, 0x00, 0x5f, 0xb0, 0x7f, 0x2a, 0x2b, 0x76, 0x54, 0x9c, 0x86, 0xf8, 0x1f, 0xdd,
	0x37, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xc7, 0x1e, 0xdb, 0xef, 0x09, 0x00, 0x00,
}
