// Code generated by protoc-gen-go. DO NOT EDIT.
// source: abci/protos/data.proto

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeDetail struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,5,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,6,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	Mq                   *MQ      `protobuf:"bytes,7,opt,name=mq,proto3" json:"mq,omitempty"`
	Active               bool     `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDetail) Reset()         { *m = NodeDetail{} }
func (m *NodeDetail) String() string { return proto.CompactTextString(m) }
func (*NodeDetail) ProtoMessage()    {}
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_d361d7f7e163c04a, []int{0}
}
func (m *NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetail.Unmarshal(m, b)
}
func (m *NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetail.Marshal(b, m, deterministic)
}
func (dst *NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetail.Merge(dst, src)
}
func (m *NodeDetail) XXX_Size() int {
	return xxx_messageInfo_NodeDetail.Size(m)
}
func (m *NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetail proto.InternalMessageInfo

func (m *NodeDetail) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *NodeDetail) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *NodeDetail) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeDetail) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *NodeDetail) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *NodeDetail) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

func (m *NodeDetail) GetMq() *MQ {
	if m != nil {
		return m.Mq
	}
	return nil
}

func (m *NodeDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type MQ struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MQ) Reset()         { *m = MQ{} }
func (m *MQ) String() string { return proto.CompactTextString(m) }
func (*MQ) ProtoMessage()    {}
func (*MQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_d361d7f7e163c04a, []int{1}
}
func (m *MQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MQ.Unmarshal(m, b)
}
func (m *MQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MQ.Marshal(b, m, deterministic)
}
func (dst *MQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQ.Merge(dst, src)
}
func (m *MQ) XXX_Size() int {
	return xxx_messageInfo_MQ.Size(m)
}
func (m *MQ) XXX_DiscardUnknown() {
	xxx_messageInfo_MQ.DiscardUnknown(m)
}

var xxx_messageInfo_MQ proto.InternalMessageInfo

func (m *MQ) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MQ) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type IdPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdPList) Reset()         { *m = IdPList{} }
func (m *IdPList) String() string { return proto.CompactTextString(m) }
func (*IdPList) ProtoMessage()    {}
func (*IdPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_d361d7f7e163c04a, []int{2}
}
func (m *IdPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPList.Unmarshal(m, b)
}
func (m *IdPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPList.Marshal(b, m, deterministic)
}
func (dst *IdPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPList.Merge(dst, src)
}
func (m *IdPList) XXX_Size() int {
	return xxx_messageInfo_IdPList.Size(m)
}
func (m *IdPList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPList.DiscardUnknown(m)
}

var xxx_messageInfo_IdPList proto.InternalMessageInfo

func (m *IdPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeDetail)(nil), "NodeDetail")
	proto.RegisterType((*MQ)(nil), "MQ")
	proto.RegisterType((*IdPList)(nil), "IdPList")
}

func init() { proto.RegisterFile("abci/protos/data.proto", fileDescriptor_data_d361d7f7e163c04a) }

var fileDescriptor_data_d361d7f7e163c04a = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xdd, 0x4a, 0xf3, 0x30,
	0x18, 0xc7, 0x49, 0xba, 0xb7, 0x1f, 0xcf, 0x0b, 0x8a, 0x11, 0x66, 0x40, 0x84, 0xd2, 0xa3, 0xe0,
	0xc1, 0x06, 0x7a, 0x05, 0x82, 0x27, 0x45, 0x37, 0xb6, 0xdc, 0x40, 0x79, 0xda, 0xe4, 0x20, 0x98,
	0x2c, 0x5d, 0x1b, 0x65, 0xbb, 0x62, 0x6f, 0x43, 0x9a, 0xcd, 0xe1, 0xd9, 0xff, 0xe3, 0x07, 0xc9,
	0xff, 0x81, 0x39, 0xb6, 0x9d, 0x59, 0xf6, 0x83, 0x0f, 0x7e, 0x5c, 0x2a, 0x0c, 0xb8, 0x88, 0xba,
	0xfa, 0x26, 0x00, 0x6b, 0xaf, 0xf4, 0xab, 0x0e, 0x68, 0x2c, 0x7b, 0x00, 0xe8, 0x3f, 0x5b, 0x6b,
	0xba, 0xe6, 0x43, 0x1f, 0x39, 0x29, 0x89, 0x28, 0x64, 0x71, 0x4a, 0xde, 0xf4, 0x91, 0x3d, 0xc2,
	0x8d, 0xc3, 0x31, 0xe8, 0xa1, 0xf9, 0x43, 0xd1, 0x48, 0x5d, 0x9f, 0x8a, 0xcd, 0x85, 0xbd, 0x87,
	0x62, 0xe7, 0x95, 0x6e, 0x76, 0xe8, 0x34, 0x4f, 0x22, 0x93, 0x4f, 0xc1, 0x1a, 0x9d, 0x66, 0x0c,
	0x66, 0x83, 0xb7, 0x9a, 0xcf, 0x62, 0x1e, 0x35, 0xbb, 0x83, 0xcc, 0xe1, 0xa1, 0x31, 0x68, 0xf9,
	0xbf, 0x92, 0x08, 0x22, 0x53, 0x87, 0x87, 0x1a, 0xed, 0x6f, 0x81, 0x68, 0x79, 0x7a, 0x29, 0x5e,
	0xd0, 0xb2, 0x5b, 0xa0, 0x6e, 0xcf, 0xb3, 0x92, 0x88, 0xff, 0x4f, 0xc9, 0x62, 0xb5, 0x95, 0xd4,
	0xed, 0xd9, 0x1c, 0x52, 0xec, 0x82, 0xf9, 0xd2, 0x3c, 0x2f, 0x89, 0xc8, 0xe5, 0xd9, 0x55, 0x02,
	0xe8, 0x6a, 0xcb, 0xae, 0x80, 0x9a, 0xfe, 0x3c, 0x8c, 0x9a, 0x7e, 0xfa, 0x48, 0xef, 0x87, 0x10,
	0x47, 0x24, 0x32, 0xea, 0xaa, 0x82, 0xac, 0x56, 0x9b, 0x77, 0x33, 0x86, 0xe9, 0xe9, 0x38, 0xc2,
	0x28, 0x4e, 0xca, 0x44, 0x14, 0x32, 0x9d, 0x6c, 0xad, 0xda, 0x34, 0x9e, 0xef, 0xf9, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x30, 0x52, 0x7a, 0x3a, 0x58, 0x01, 0x00, 0x00,
}
